 
// Commands (ID_* and IDM_*) 
#define HID_TAKE_JPEG                           0x10002
#define HID_TASK_TIMER                          0x10007
#define HID_TESTACQUIRE                         0x1052A
#define HID_DELETESETTINGS                      0x10537
#define HID_DE_autosaverawFrames                0x10767
#define HID_DE_waterlineTemp                    0x1076B
#define HID_DE_autosaveSummedImages             0x107DA
#define HID_DE_camName                          0x107E3
#define HID_TAKE_TIFF                           0x10A1F
#define HID_NEW_IMAGE                           0x18003
#define HIDM_FILE_SAVEOTHER                     0x18004
#define HIDM_FILE_READ                          0x18005
#define HIDM_FILE_OPENNEW                       0x18007
#define HIDM_FILE_OPENOLD                       0x18008
#define HID_FILE_MONTAGESETUP                   0x18009
#define HIDM_FILE_MONTAGESETUP                  0x1800A
#define HIDM_FILE_CLOSE                         0x1800B
#define HIDM_FILE_SAVEACTIVE                    0x1800C
#define HIDM_FILE_TRUNCATION                    0x1800D
#define HIDM_FILE_READOTHER                     0x1800F
#define HIDM_FILE_SAVE                          0x18010
#define HID_RESIZE_MAIN                         0x18011
#define HID_CAMERA_PARAMETERS                   0x18012
#define HID_CAMERA_ACQUIRE                      0x18013
#define HID_CAMERA_VIEW                         0x18014
#define HID_CAMERA_FOCUS                        0x18015
#define HID_CAMERA_TRIAL                        0x18016
#define HID_CAMERA_RECORD                       0x18017
#define HID_CAMERA_SCREENDOWN                   0x18018
#define HID_CAMERA_SIMULATION                   0x18019
#define HID_CAMERA_STOPACQUIRE                  0x1801A
#define HID_SETTINGS_OPEN                       0x1801B
#define HID_SETTINGS_REREAD                     0x1801C
#define HID_SETTINGS_SAVE                       0x1801D
#define HID_SETTINGS_SAVEAS                     0x1801E
#define HID_SETTINGS_CLOSE                      0x1801F
#define HID_SETTINGS_RESTOREDEFAULTS            0x18020
#define HID_SETTINGS_READAGAIN                  0x18021
#define HID_SETTINGS_READDEFAULTS               0x18022
#define HID_SETTINGS_SAVECALIBRATIONS           0x18023
#define HID_CALIBRATION_IMAGESHIFT              0x18024
#define HID_FILE_OVERWRITE                      0x18025
#define HID_FILE_READPIECE                      0x18026
#define HID_CAMERA_MONTAGE                      0x18027
#define HID_CAMERA_MONTAGETRIAL                 0x18028
#define HIDM_AUTOALIGN                          0x18029
#define HIDM_TILTUP                             0x1802A
#define HIDM_TILTDOWN                           0x1802B
#define HID_FILE_OPENLOG                        0x1802C
#define HID_FILE_SAVELOG                        0x1802D
#define HID_CALIBRATION_AUTOFOCUS               0x1802E
#define HID_CALIBRATION_ADMINISTRATOR           0x1802F
#define HID_FOCUS_SETTARGET                     0x18030
#define HID_FOCUS_MEASUREDEFOCUS                0x18031
#define HID_FOCUS_AUTOFOCUS                     0x18032
#define HID_FOCUS_SETBEAMTILT                   0x18033
#define HID_FOCUS_SETTHRESHOLD                  0x18034
#define HID_FOCUS_REPORTSHIFTDRIFT              0x18035
#define HID_FOCUS_DRIFTPROTECTION               0x18036
#define HID_MACRO_EDIT1                         0x18037
#define HID_MACRO_EDIT2                         0x18038
#define HID_MACRO_EDIT3                         0x18039
#define HID_MACRO_EDIT4                         0x1803A
#define HID_MACRO_EDIT5                         0x1803B
#define HID_MACRO_EDIT6                         0x1803C
#define HID_MACRO_EDIT7                         0x1803D
#define HID_MACRO_EDIT8                         0x1803E
#define HID_MACRO_EDIT9                         0x1803F
#define HID_MACRO_EDIT10                        0x18040
#define HID_MACRO_STOP                          0x1804B
#define HID_MACRO_END                           0x1804C
#define HID_MACRO_RESUME                        0x1804D
#define HID_MACRO_CONTROLS                      0x1804E
#define HID_CALIBRATION_SETSHIFTDELAY           0x1804F
#define HID_CALIBRATION_SETFOCUSRANGE           0x18050
#define HIDM_CAMERATOGGLE                       0x1805D
#define HID_WINDOW_RESIZEMAIN                   0x1805F
#define HID_FILE_SAVELOGAS                      0x18060
#define HID_CALIBRATION_BEAMINTENSITY           0x18061
#define HID_PROCESS_MINMAXMEAN                  0x18062
#define HID_PROCESS_FFT                         0x18063
#define HID_PROCESS_BINNEDFFT                   0x18064
#define HID_PROCESS_ROTATELEFT                  0x18065
#define HID_PROCESS_ROTATERIGHT                 0x18066
#define HID_EUCENTRICITY_COARSE                 0x18067
#define HID_EUCENTRICITY_FINE                   0x18068
#define HID_EUCENTRICITY_BOTH                   0x18069
#define HID_CALIBRATION_ISFROMSCRATCH           0x1806A
#define HID_REVERSE_TILT                        0x1806B
#define HID_PROCESS_ZEROTILTMEAN                0x1806C
#define HID_CAMERA_POSTACTIONS                  0x1806E
#define HID_TASKS_TILTSERIES                    0x1806F
#define HID_PROCESS_SETINTENSITY                0x18070
#define HID_TASKS_FINEREALIGN                   0x18071
#define HID_FOCUS_MOVEFOCUSCENTER               0x18072
#define HID_FOCUS_MOVECENTER                    0x18073
#define HID_TILTSERIES_STOP                     0x18074
#define HID_TILTSERIES_ENDLOOP                  0x18075
#define HID_TILTSERIES_RESUME                   0x18076
#define HID_TILTSERIES_BACKUP                   0x18077
#define HID_TILTSERIES_ONELOOP                  0x18078
#define HID_TILTSERIES_ONESTEP                  0x18079
#define HID_TILTSERIES_TERMINATE                0x1807A
#define HID_FOCUS_VERBOSE                       0x1807B
#define HID_TASKS_VERBOSE                       0x1807C
#define HID_TILTSERIES_VERBOSE                  0x1807D
#define HID_CAMERA_PREVIEW                      0x1807E
#define HID_CALIBRATION_BEAMSHIFT               0x1807F
#define HID_PROCESS_MOVEBEAM                    0x18080
#define HID_CAMERA_SETTIMING                    0x18081
#define HID_CAMERA_DEBUGMODE                    0x18082
#define HID_CAMERA_NEWGAINREF                   0x18083
#define HID_CAMERA_SHOWGAINREF                  0x18084
#define HID_CAMERA_SHOWDARKREF                  0x18085
#define HID_CALIBRATION_MAGENERGYSHIFTS         0x18086
#define HID_PROCESS_FIXDARKXRAYS                0x18087
#define HID_PROCESS_SETDARKCRITERIA             0x18089
#define HID_CAMERA_ACQUIREGAINREF               0x1808B
#define HID_FOCUS_CHECKAUTOFOCUS                0x1808C
#define HID_TILTSERIES_DEBUGMODE                0x1808D
#define HID_CALIBRATION_LISTMAGS                0x1808E
#define HID_TILTSERIES_AUTOSAVELOG              0x1808F
#define HID_FOCUS_REPORTONEXISTING              0x18090
#define HID_FOCUS_SETOFFSET                     0x18091
#define HID_TASKS_WALKUPANCHOR                  0x18092
#define HID_CALIBRATION_DISTORTION              0x18093
#define HID_CALIBRATION_STAGESHIFT              0x18094
#define HID_TASKS_NAVIGATOR                     0x18095
#define HID_LOAD_NAV_FILE                       0x18098
#define HID_NAVIGATOR_CLOSE                     0x18099
#define HID_CALIBRATION_ELECTRONDOSE            0x1809C
#define HID_CALIBRATION_C2FACTOR                0x1809D
#define HID_FILE_SET16BITPOLICY                 0x1809E
#define HID_CALIBRATION_BEAMCROSSOVER           0x1809F
#define HID_CALIBRATION_SETOVERLAPS             0x180A0
#define HID_NAVIGATOR_AUTOSAVE                  0x180A1
#define HID_SETTINGS_AUTOSAVE                   0x180A2
#define HID_NAVIGATOR_SETUPFULLMONTAGE          0x180A3
#define HID_TASKS_SETTILTAXISOFFSET             0x180A4
#define HID_CAMERA_DIVIDEBY2                    0x180A5
#define HID_CALIBRATION_CAMERATIMING            0x180A7
#define HID_CAMERA_SETCORRECTIONS               0x180A8
#define HID_CAMERA_NORMALIZEHERE                0x180A9
#define HID_FOCUS_RESETDEFOCUS                  0x180AA
#define HID_TASKS_SETITERATIONLIMIT             0x180AB
#define HID_TASKS_USETRIALINLD                  0x180AC
#define HID_NAVIGATOR_CONVERTMAPSTOBYTES        0x180AD
#define HID_CAMERA_SETSCANNING                  0x180AE
#define HID_CALIBRATION_NEUTRALISVALUES         0x180AF
#define HID_FILE_SETSIGNEDPOLICY                0x180B0
#define HID_CALIBRATION_SPOTINTENSITY           0x180B1
#define HID_CALIBRATION_PURGEOLDCALIBS          0x180B2
#define HID_NAVIGATOR_SKEWEDSUPERMONTAGE        0x180B3
#define HID_NAVIGATOR_ALIGNEDSUPERMONTAGE       0x180B4
#define HID_CALIBRATION_LISTISVECTORS           0x180B5
#define HID_FILE_READAPPEND                     0x180B6
#define HID_PROCESS_FIXIMAGEXRAYS               0x180B7
#define HID_PROCESS_SETIMAGECRITERIA            0x180B8
#define HID_CALIBRATION_LISTSTAGECALS           0x180B9
#define HID_CALIBRATION_SHUTTERDEADTIME         0x180BA
#define HID_PROCESS_SHOWCROSSCORR               0x180BB
#define HID_CALIBRATION_SETDEBUGOUTPUT          0x180BC
#define HID_SETTINGS_MRU_FILE1                  0x180BD
#define HID_SETTINGS_MRU_FILE2                  0x180BE
#define HID_SETTINGS_MRU_FILE3                  0x180BF
#define HID_SETTINGS_MRU_FILE4                  0x180C0
#define HID_SETTINGS_MRU_FILE5                  0x180C1
#define HID_SETTINGS_MRU_FILE6                  0x180C2
#define HID_SETTINGS_MRU_FILE7                  0x180C3
#define HID_SETTINGS_MRU_FILE8                  0x180C4
#define HID_FILE_NEWMONTAGE                     0x180C5
#define HID_TILTSERIES_EXTRAOUTPUT              0x180C6
#define HID_PROCESS_LIVEFFT                     0x180C7
#define HID_NAVIGATOR_RUNMACROATAREAS           0x180C8
#define HID_Menu                                0x180C9
#define HID_FOCUS_SHOWEXISTINGCORR              0x180CA
#define HID_NAVIGATOR_CHANGEREGISTRATION        0x180D3
#define HID_CALIBRATION_MAGISOFFSETS            0x180D4
#define HID_CALIBRATION_EFTEMISOFFSET           0x180D5
#define HID_TASKS_CENTERBEAM                    0x180D6
#define HID_NAVIGATOR_ROTATEMAP                 0x180DB
#define HID_NAVIGATOR_ALIGNTOITEM               0x180DC
#define HID_NAVIGATOR_SHIFTBYLASTERROR          0x180DD
#define HID_NAVIGATOR_REALIGNACQUIRE            0x180DE
#define HID_NAVIGATOR_SHIFTTOMARKER             0x180DF
#define HID_NAVIGATOR_UNDOLASTSHIFT             0x180E0
#define HID_NAVIGATOR_LOADUNBINNED              0x180E2
#define HID_NAVIGATOR_SETGRIDLIMITS             0x180E3
#define HID_CALIBRATION_STANDARDLMFOCUS         0x180E4
#define HID_CAMERA_GAINREFPOLICY                0x180E6
#define HID_TILTSERIES_RESETPOLEANGLE           0x180E7
#define HID_MACRO_TOOLBAR                       0x180E8
#define HID_Menu33001                           0x180E9
#define HID_TILTSERIES_SETUPFUTURE              0x180EA
#define HID_TILTSERIES_FUTUREPOLICIES           0x180EB
#define HID_NAVIGATOR_ENDACQUIRE                0x180EC
#define HID_PROCESS_CIRCLEONLIVEFFT             0x180ED
#define HID_NAVIGATOR_RESTORESTATE              0x180F0
#define HID_NAVIGATOR_SETACQUIRESTATE           0x180F1
#define HID_TASKS_SETINCREMENTS                 0x180F2
#define HID_NAVIGATOR_READSTOCKSTATES           0x180F3
#define HID_NAVIGATOR_ADDCIRCLEPOLYGON          0x180F5
#define HID_NAVIGATOR_DELETESUPERMONTAGE        0x180F6
#define HID_NAVIGATOR_SUPERMONTAGING            0x180F7
#define HID_SUPERMONTAGING_POLYGONSUPERMONTAGE  0x180F8
#define HID_MACRO_EDIT25                        0x180F9
#define HID_MACRO_EDIT30                        0x180FA
#define HID_MACRO_EDIT35                        0x180FB
#define HID_MACRO_EDIT40                        0x180FC
#define HID_MACRO_EDIT45                        0x180FD
#define HID_MACRO_EDIT50                        0x180FE
#define HID_MACRO_EDIT55                        0x180FF
#define HID_MACRO_EDIT60                        0x18100
#define HID_MACRO_SET                           0x1810D
#define HID_MACRO_SETLENGTH                     0x1810E
#define HID_NAVIGATOR_IMPORTMAP                 0x1810F
#define HID_NAVIGATOR_UNDOTRANSFORMATION        0x18110
#define HID_MONTAGE_DEFINEFILETOOPEN            0x18111
#define HID_NAVIGATOR_ADDGRIDOFPOINTS           0x18112
#define HID_MONTAGE_LISTFILESTOOPEN             0x18113
#define HID_CAMERA_SETCOUNTLIMIT                0x18114
#define HID_TASKS_SETUPCOOKER                   0x18115
#define HID_TASKS_COOKSPECIMEN                  0x18116
#define HID_TASKS_SETUPAUTOCENTER               0x18117
#define HID_TASKS_AUTOCENTERBEAM                0x18118
#define HID_CALIBRATION_USESHORT                0x1811B
#define HID_PROCESS_FINDPIXELSIZE               0x1811D
#define HID_PROCESS_PIXELSIZEFROMMARKER         0x1811E
#define HID_CAMERA_SETDRIFTINTERVAL             0x1811F
#define HID_FILE_CONTINUOUSSAVE                 0x18120
#define HID_MACRO_VERBOSE                       0x18121
#define HID_TILTSERIES_SENDEMAIL                0x18124
#define HID_TILTSERIES_SETADDRESS               0x18125
#define HID_PROCESS_MAKECOLOROVERLAY            0x18126
#define HID_TASKS_ASSESSANGLERANGE              0x18127
#define HID_NAVIGATOR_OPENSTATEDLG              0x18128
#define HID_NAVIGATOR_GROUP_ACQUIRE             0x1812A
#define HID_TASKS_TRIAL_IN_LD_REFINE            0x1812D
#define HID_NAVIGATOR_ALIGN_TO_MAP              0x1812F
#define HID_CAMERA_INTERPOLATE_DARK_REFS        0x18131
#define HID_PROCESS_CROPIMAGE                   0x18132
#define HID_CALIBRATION_STAGESTRETCH            0x18133
#define HID_PROCESS_LISTRELATIVEROTATIONS       0x18134
#define HID_NEW_MAP                             0x1813D
#define HID_NAVIGATOR_ACQUIRE                   0x1813E
#define HID_DELETEITEM                          0x1813F
#define HID_SAVE_NAV_FILE                       0x18140
#define HID_SAVEAS_NAV_FILE                     0x18141
#define HID_CORNER_MONTAGE                      0x18142
#define HID_POLYGON_MONTAGE                     0x18143
#define HID_TRANSFORM_PTS                       0x18144
#define HID_TASKS_WALKUP                        0x18146
#define HID_RESET_REALIGN                       0x18147
#define HID_MACRO_EDIT15                        0x18148
#define HID_MACRO_EDIT20                        0x18149
#define HID_CALIBRATION_SET_IS_DELAY_FACTOR     0x1814B
#define HID_NAVIGATOR_POLYGON_FROM_CORNERS      0x1814D
#define HID_CALIBRATION_STEMFOCUSVSZ            0x1814F
#define HID_TASKS_ASSESS_INTERSET_SHIFTS        0x18154
#define HID_TASKS_REVISE_CANCEL                 0x18156
#define HID_NAVIGATOR_REALIGN_SCALING           0x18158
#define HID_CALIBRATION_QUICK_FLYBACK_TIME      0x1815A
#define HID_PROCESS_SETBINNEDSIZE               0x1815B
#define HID_NAVIGATOR_ADJUST_BACKLASH           0x1815D
#define HID_NAVIGATOR_BACKLASHSETTINGS          0x1815E
#define HID_TASKS_USE_VIEW_IN_LOWDOSE           0x18160
#define HID_CALIBRATION_ALPHA_BEAM_SHIFTS       0x18162
#define HID_PROCESS_AUTOCORRELATION             0x18163
#define HID_DE_autosaveF                        0x18164
#define HID_DE_preExpTime                       0x18165
#define HID_DE_sensorDelay                      0x18166
#define HID_DE_currfps                          0x18167
#define HID_DE_maxfps                           0x18168
#define HID_DE_failsafe                         0x18169
#define HID_DE_protectMode                      0x1816A
#define HID_DE_coverDelay                       0x1816B
#define HID_DE_autosaveCorRaw                   0x1816C
#define HID_DE_autosaveCorrSum                  0x1816D
#define HID_DE_saveDir                          0x1816E
#define HID_DE_temperSet                        0x1816F
#define HID_DE_PROPERTY_EXPAND                  0x18175
#define HID_DE_cameraPos                        0x18177
#define HID_DE_insertCam                        0x18178
#define HID_DE_retractCam                       0x18179
#define HID_DE_antosaveFinal                    0x1817A
#define HID_CALIBRATION_SET_APERTURE_SIZE       0x1817C
#define HID_CAMERA_SAVERAWPACKED                0x1817D
#define HID_FOCUS_SET_TILT_DIRECTION            0x1817F
#define HID_CALIBRATION_WHOLE_IMAGE_CORR        0x18181
#define HID_CALIBRATION_SET_CYCLE_LENGTHS       0x18187
#define HID_CALIBRATION_BEAMSPOT                0x18188
#define HID_CALIBRATION_PIXELSIZE               0x1818A
#define HID_PIXELSIZE_ADD_TO_ROTATION           0x1818C
#define HID_MACRO_RUN                           0x1818D
#define HID_TASKS_SETDOSERATE                   0x18198
#define HID_TASKS_SET_DOSE_RATE                 0x18199
#define HID_FILE_CLOSE_MDOC                     0x1819C
#define HID_FILE_OPEN_MDOC                      0x1819D
#define HID_MACRO_READMANY                      0x1819E
#define HID_MACRO_WRITEALL                      0x1819F
#define HID_TILTSERIES_CALL_TS_PLUGIN           0x181A1
#define HID_SETTINGS_SPECIALOPTIONS             0x181A2
#define HID_SPECIAL_PIEZO_FOR_LD_AXIS_SHIFT     0x181A5
#define HID_SPECIAL_SKIP_BEAM_SHIFT_IN_TS       0x181A6
#define HID_TASKS_SPECIALOPTIONS                0x181A7
#define HID_PIXELSIZE_CATALASE_CRYSTAL          0x181A9
#define HID_NAVIGATOR_MERGEFILE                 0x181AA
#define HID_CAMERA_SPECIALSETTINGS              0x181AB
#define HID_SPECIALSETTINGS_SETQUALITY          0x181AC
#define HID_CAMERA_SET_QUALITY                  0x181AD
#define HID_WINDOW_STAGE_MOVE_TOOL              0x181AF
#define HID_PROCESS_CROP_AVERAGE                0x181B1
#define HID_NAVIGATOR_FORCE_CENTER_ALIGN        0x181B3
#define HID_SPECIAL_DISABLE_DARK_TRIM_IN_ALIGN  0x181B6
#define HID_AUTOFOCUSFOCUS_LISTCALIBRATIONS     0x181B7
#define HID_FOCUS_SET_DDD_MIN_BINNING           0x181B9
#define HID_FOCUS_SET_FILTER_CUTOFFS            0x181BC
#define HID_CALIBRATION_BASEFOCUS               0x181BD
#define HID_AUTOFOCUSFOCUS_BASEFOCUSVALUES      0x181BE
#define HID_CALIBRATION_RESTORENEUTRALIS        0x181BF
#define HID_PIXELSIZE_MESHFORGRIDBARS           0x181C0
#define HID_BEAMSPOT_SPOTBEAMSHIFTS             0x181C1
#define HID_BEAMSPOT_RESTORESPOTSHIFTS          0x181C2
#define HID_SPECIALOPTIONS_ALLOWCONTINUOUSINTASKS	0x181C3
#define HID_SPECIALOPTIONS_NORMALIZEVIAVIEWFORAU	0x181C4
#define HID_MONTAGINGGRIDS_GROUPPOINTSINGRID    0x181C5
#define HID_MONTAGINGGRIDS_SETGROUPSIZE         0x181C6
#define HID_FOCUS_SHOWEXISTINGSTRETCH           0x181C7
#define HID_IMAGESTAGESHIFT_USETRIALBINNING     0x181C8
#define HID_IMAGESTAGESHIFT_USETRIALSIZE        0x181C9
#define HID_PROCESS_SIDE                        0x181CA
#define HID_PROCESS_SIDE_BY_SIDE                0x181CB
#define HID_IMAGESTAGESHIFT_REMOVEISCAL         0x181CD
#define HID_IMAGESTAGESHIFT_REMOVESTAGECAL      0x181CE
#define HID_SPECIALOPTIONS_ADJUSTFOCUSONPROBEMODECHANGE	0x181CF
#define HID_TILTSERIES_SAVEX                    0x181D0
#define HID_CAMERA_NONORMOFDSDOSEFRAC           0x181D1
#define HID_TILTSERIES_AUTOSAVEX                0x181D2
#define HID_MACRO_LISTFUNCTIONS                 0x181D3
#define HID_AUTOFOCUSFOCUS_ASTIGMATI            0x181D4
#define HID_AUTOFOCUSFOCUS_COMA                 0x181D5
#define HID_FOCUS_CORRECTASTIGMATISM            0x181D6
#define HID_FOCUS_COMA                          0x181D7
#define HID_AUTOFOCUSFOCUS_SETUPCOMA            0x181D8
#define HID_AUTOFOCUSFOCUS_SETUPASTIGMATISM     0x181D9
#define HID_FOCUS_SETASTIGBEAMTILT              0x181DA
#define HID_FOCUS_SETCOMABEAMTILT               0x181DB
#define HID_TILTSERIES_PRE                      0x181DC
#define HID_TILTSERIES_RUN_MACRO                0x181DD
#define HID_TILTSERIES_SETMACROTORUN            0x181DE
#define HID_CAMERA_CORRELATIONFILTER            0x181DF
#define HID_CORRELATIONFILTER_USEFILTERSET2     0x181E0
#define HID_CORRELATIONFILTER_USESET2INLOWDOSE  0x181E1
#define HID_CORRELATIONFILTER_DIVIDESET1BY2     0x181E2
#define HID_CORRELATIONFILTER_DIVIDEFILTERSET2BY2	0x181E3
#define HID_CORRELATIONFILTER_TESTSET1VALUES    0x181E4
#define HID_CORRELATIONFILTER_TESTSET2VALUES    0x181E5
#define HID_CORRELATIONFILTER_REDOCORRWHENREAD  0x181E6
#define HID_IMAGESTAGESHIFT_DOFOCUS             0x181E7
#define HID_CALIBRATION_HIGH                    0x181E8
#define HID_CALIBRATION_HIGH_DEFOCUS            0x181E9
#define HID_CALIBRATION_LISTFOCUS               0x181EA
#define HID_PROCESS_AUTOMATICFFTS               0x181EB
#define HID_PROCESS_SETPHASEPLATESHIFT          0x181EC
#define HID_PROCESS_SETDEFOCUSFORCIRCLES        0x181ED
#define HID_TILTSERIES_FIXED                    0x181EE
#define HID_TILTSERIES_FIXED_NUM_FRAMES         0x181EF
#define HID_NAVIGATOR_WRITEASXMLFILE            0x181F0
#define HID_WINDOW_SHOWSCOPECONTROLPANEL        0x181F1
#define HID_NAVIGATOR_OPTIONS                   0x181F2
#define HID_OPTIONS_SETPOINTLABELTHRESHOLD      0x181F3
#define HID_FOCUS_SETABSOLUTELIIMITS            0x181F4
#define HID_FOCUS_USEABSOLUTERANGE              0x181F5
#define HID_FOCUS_TESTWHENUSINGOFFSET           0x181F6
#define HID_CAMERA_SETFRAMEALIGNLINES           0x181F7
#define HID_SETTINGS_SETAPROPERTY               0x181F8
#define HID_FOCUS_SETITERATIONS                 0x181F9
#define HID_FOCUS_RUNANOTHERITERATION           0x181FA
#define HID_FOCUS_MAKEZEMLINTABLEAU             0x181FB
#define HID_FOCUS_SETCOMAITERATIONS             0x181FC
#define HID_SCRIPT_SETINDENTSIZE                0x181FD
#define HID_SPECIALOPTIONS_NORMALIZEALLLENS     0x181FE
#define HID_NAVOPTIONS_USECURRENTLDPARAMSINRI   0x181FF
#define HID_CAMERA_USEVIEWFORSEARCH             0x18200
#define HID_CAMERA_USERECORDFORMONTAGE          0x18201
#define HID_CAMERA_SEARCH                       0x18202
#define HID_SCRIPT_CLEARPERSISTENTVARS          0x18204
#define HID_OPTIONS_SHOWMULTI                   0x18205
#define HID_OPTIONS_SETMULTI                    0x18206
#define HID_Menu33287                           0x18207
#define HID_SCRIPT_RUNONECOMMAND                0x18208
#define HID_FILE_SKIPFILEPROPERTIESDIALOG       0x18209
#define HID_PROCESS_REDUCEIMAGE                 0x1820A
#define HID_PROCESS_DOCTFFINDFITONCLICK         0x1820B
#define HID_PROCESS_SETCTFFINDOPTIONS           0x1820C
#define HID_FOCUSTUNING_CTF                     0x1820E
#define HID_FOCUS_COMA33295                     0x1820F
#define HID_FOCUS_CORRECTASTIGMATISMWITHFFTS    0x18210
#define HID_FOCUS_SETCTFACQUIREPARAMS           0x18211
#define HID_FOCUS_COMA_BY_CTF                   0x18212
#define HID_FOCUS_BTIDCOMA                      0x18213
#define HID_BTIDCOMA_OLDCOMA                    0x18214
#define HID_FOCUS_SETCOMA                       0x18215
#define HID_FOCUS_SET_CTF_COMA_BT               0x18216
#define HID_FOCUSTUNING_COMAVS                  0x18217
#define HID_MONTAGINGGRIDS_SHOWWHOLEAREAFORALLPOINTS	0x18218
#define HID_MONTAGINGGRIDS_ADDGRIDLIKELASTONE   0x18219
#define HID_SCRIPT_OPENEDITORSONSTART           0x1821A
#define HID_SETTINGS_DISCARDONEXIT              0x1821B
#define HID_EXTERNAL_TOOL1                      0x1821C
#define HID_EXTERNAL_TOOL2                      0x1821D
#define HID_EXTERNAL_TOOL3                      0x1821E
#define HID_EXTERNAL_TOOL4                      0x1821F
#define HID_EXTERNAL_TOOL5                      0x18220
#define HID_EXTERNAL_TOOL6                      0x18221
#define HID_EXTERNAL_TOOL7                      0x18222
#define HID_EXTERNAL_TOOL8                      0x18223
#define HID_EXTERNAL_TOOL9                      0x18224
#define HID_EXTERNAL_TOOL10                     0x18225
#define HID_EXTERNAL_TOOL11                     0x18226
#define HID_EXTERNAL_TOOL12                     0x18227
#define HID_EXTERNAL_TOOL13                     0x18228
#define HID_EXTERNAL_TOOL14                     0x18229
#define HID_EXTERNAL_TOOL15                     0x1822A
#define HID_EXTERNAL_TOOL16                     0x1822B
#define HID_EXTERNAL_TOOL17                     0x1822C
#define HID_EXTERNAL_TOOL18                     0x1822D
#define HID_EXTERNAL_TOOL19                     0x1822E
#define HID_EXTERNAL_TOOL20                     0x1822F
#define HID_EXTERNAL_TOOL21                     0x18230
#define HID_EXTERNAL_TOOL22                     0x18231
#define HID_EXTERNAL_TOOL23                     0x18232
#define HID_EXTERNAL_TOOL24                     0x18233
#define HID_EXTERNAL_TOOL25                     0x18234
#define HID_SPECIALSETTINGS_ALWAYSANTIALIASK2   0x18235
#define HID_BEAMSPOT_LISTCALIBRATIONS           0x18236
#define HID_TASKS_SETUPWAITFORDRIFT             0x18237
#define HID_SPECIALIZEDOPTIONS_SKIPBLANKINGINLDWITHSCREENUP	0x18275
#define HID_TASKS_SETUPVPPCONDITIONING          0x18276
#define HID_WINDOW_TAKESCREENSHOT               0x18277
#define HID_SCRIPT_LISTPERSISTENTVARS           0x18278
#define HID_SCRIPT_LOADNEWPACKAGE               0x18279
#define HID_SCRIPT_SAVEPACKAGE                  0x1827A
#define HID_SCRIPT_SAVEPACKAGEAS                0x1827B
#define HID_SCRIPT_EDIT                         0x1827C
#define HID_MONTAGINGGRIDS_FINDREGULARARRAYOFHOLES	0x1827D
#define HID_MONTAGINGGRIDS_COMBINEPOINTSINTOMULTI	0x1827E
#define HID_CAMERA_SETEXTRADIVISIONBY2          0x1827F
#define HID_CAMERA_RETURNFLOATIMAGE             0x18280
#define HID_CAMERA_                             0x18281
#define HID_BEAMSPOT_REFINEBEAMSHIFT            0x18282
#define HID_BEAMSPOT_ILLUMINATEDAREALIMITS      0x18283
#define HID_WINDOW_RESCUELOGWINDOW              0x18284
#define HID_OPTIONS_SEARCH                      0x18285
#define HIDM_MARKER_TO_CENTER                   0x18286
#define HID_SETTINGS_BASICMODE                  0x18287
#define HID_SCRIPT_RUNONPROGRAMSTART            0x18288
#define HID_SCRIPT_RUNATPROGRAMEND              0x18289
#define HID_OPTIONS_USEITEMLABELSINFILENAMES    0x1828A
#define HID_SPECIALIZEDOPTIONS_CLOSEVALVESAFTERLONGINACTIVITY	0x1828B
#define HID_TASKS_ROUGHUSESEARCHIFINLM          0x1828C
#define HID_SCRIPT_USEMONOSPACEDFONT            0x1828D
#define HID_SCRIPT_SHOWINDENTBUTTONS            0x1828E
#define HID_NAVIGATOR_APPLYSAVEDSHIFT           0x1828F
#define HID_TASKS_EUCENTRICITY                  0x18290
#define HID_EUCENTRICITY_EUCENTRICITYBYFOCUS    0x18291
#define HID_EUCENTRICITY_SETUPEUCENTRICITYBYFOCUS	0x18292
#define HID_NAVIGATOR_SETUPALIGN                0x18293
#define HID_TASKS_SETUPSCOPEMANAGEMENT          0x18294
#define HID_FOCUSTUNING_EXTENDEDAUTOFOCUS       0x18295
#define HID_FOCUSTUNING_SETEXTENDEDRANGE        0x18296
#define HID_FILE_USEMONOSPACEDFONT              0x18297
#define HID_SPECIALIZEDOPTIONS_TASKSUSEVIEWEVENIFSEARCHBETTER	0x18298
#define HID_SPECIALIZEDOPTIONS_KEEPFOCUSTRIALSTSAMEPOSITION	0x18299
#define HID_TILTSERIES_SETBIDIRRETURNDELAY      0x1829A
#define HID_MACRO_RUN1                          0x1829D
#define HID_MACRO_RUN2                          0x1829E
#define HID_MACRO_RUN3                          0x1829F
#define HID_MACRO_RUN4                          0x182A0
#define HID_MACRO_RUN5                          0x182A1
#define HID_MACRO_RUN6                          0x182A2
#define HID_MACRO_RUN7                          0x182A3
#define HID_MACRO_RUN8                          0x182A4
#define HID_MACRO_RUN9                          0x182A5
#define HID_MACRO_RUN10                         0x182A6
#define HID_MACRO_RUN11                         0x182A7
#define HID_MACRO_RUN12                         0x182A8
#define HID_MACRO_RUN13                         0x182A9
#define HID_MACRO_RUN14                         0x182AA
#define HID_MACRO_RUN15                         0x182AB
#define HID_MACRO_RUN16                         0x182AC
#define HID_MACRO_RUN17                         0x182AD
#define HID_MACRO_RUN18                         0x182AE
#define HID_MACRO_RUN19                         0x182AF
#define HID_MACRO_RUN20                         0x182B0
#define HID_MACRO_RUN21                         0x182B1
#define HID_MACRO_RUN22                         0x182B2
#define HID_MACRO_RUN23                         0x182B3
#define HID_MACRO_RUN24                         0x182B4
#define HID_MACRO_RUN25                         0x182B5
#define HID_MACRO_RUN26                         0x182B6
#define HID_MACRO_RUN27                         0x182B7
#define HID_MACRO_RUN28                         0x182B8
#define HID_MACRO_RUN29                         0x182B9
#define HID_MACRO_RUN30                         0x182BA
#define HID_MACRO_RUN31                         0x182BB
#define HID_MACRO_RUN32                         0x182BC
#define HID_MACRO_RUN33                         0x182BD
#define HID_MACRO_RUN34                         0x182BE
#define HID_MACRO_RUN35                         0x182BF
#define HID_MACRO_RUN36                         0x182C0
#define HID_MACRO_RUN37                         0x182C1
#define HID_MACRO_RUN38                         0x182C2
#define HID_MACRO_RUN39                         0x182C3
#define HID_MACRO_RUN40                         0x182C4
#define HID_MACRO_RUN41                         0x182C5
#define HID_MACRO_RUN42                         0x182C6
#define HID_MACRO_RUN43                         0x182C7
#define HID_MACRO_RUN44                         0x182C8
#define HID_MACRO_RUN45                         0x182C9
#define HID_MACRO_RUN46                         0x182CA
#define HID_MACRO_RUN47                         0x182CB
#define HID_MACRO_RUN48                         0x182CC
#define HID_MACRO_RUN49                         0x182CD
#define HID_MACRO_RUN50                         0x182CE
#define HID_MACRO_RUN51                         0x182CF
#define HID_MACRO_RUN52                         0x182D0
#define HID_MACRO_RUN53                         0x182D1
#define HID_MACRO_RUN54                         0x182D2
#define HID_MACRO_RUN55                         0x182D3
#define HID_MACRO_RUN56                         0x182D4
#define HID_MACRO_RUN57                         0x182D5
#define HID_MACRO_RUN58                         0x182D6
#define HID_MACRO_RUN59                         0x182D7
#define HID_MACRO_RUN60                         0x182D8
#define HID_FILE_CLOSEALLFILES                  0x182D9
#define HID_TASKS_CALIBRATEELECTRONDOSE         0x182DA
#define HID_FILE_AUTOSAVELOG                    0x182DB
#define HID_SCRIPT_SETPANELROWS                 0x182DC
#define HID_SETTINGS_READBASICMODEFILE          0x182DD
#define HID_HELP_RUNSERIALEMSNAPSHOT            0x182DE
#define HID_CORRELATIONFILTER_SETPARAMSFORGRIDMAP	0x182DF
#define HID_MONTAGINGGRIDS_AUTOCONTOURGRIDSQUARES	0x182E0
#define HID_MONTAGINGGRIDS_REVERSECONTOURCOLORS 0x182E1
#define HID_MONTAGINGGRIDS_KEEPCOLORSFORPOLYGONS	0x182E2
#define HID_IMAGESTAGESHIFT_HIGH                0x182E3
#define HID_MONTAGINGGRIDS_SETHOLEORDERFORREGULARARRAY	0x182E4
#define HID_SCRIPT_RUNIFPROGRAMIDLE             0x182E5
#define HID_SCRIPT_SET                          0x182E6
#define HID_SCRIPT_SET_NUM_STATUS               0x182E7
#define HID_SCRIPT_MONOSPACESTATUSLINES         0x182E8
#define HID_SCRIPT_KEEPFOCUSONONELINE           0x182E9
#define HID_FILE_SETCURRENTDIRECTORY            0x182EA
#define HID_SETTINGS_MISCELLANEOUSOPTIONS       0x182EB
#define HID_MISCELLANEOUSOPTIONS_REVERSEWHEELZOOMDIRECTION	0x182EC
#define HID_NAVIGATOR_ERASEPERIODICCORR         0x182EE
#define HID_FILE_AUTOPRUNELOGWINDOW             0x182F0
#define HID_NAV_RUNSCRIPTINMULTISHOTACQUIRE     0x182F1
#define HID_NAV_SETSCRIPTTORUN                  0x182F2
#define HID_FILE_LOWWINDOW                      0x182F3
#define HID_LOGWINDOW_USERTFFORMATTOSAVE        0x182F4
#define HID_MONTAGINGGRIDS_MULTIPLEGRIDOPERATIONS	0x182F5
#define HID_MONTAGINGGRIDS_READSESSIONFILE      0x182F6
#define HID_MONTAGINGGRIDS_CLEARSESSION         0x182F7
#define HID_MONTAGINGGRIDS_IDENTIFYGRIDONSTAGE  0x182F8
#define HID_EUCENTRICITY_SETOFFSETAUTOMATICALLY 0x182F9
#define HID_MONTAGINGGRIDS_LOADALLGRIDMAPS      0x182FA
#define HID_CAMERA_PREVIEWPRESCAN               0x182FB
#define HID_LOGWINDOW_SAVESECONDARYLOG          0x182FC
#define HID_LOGWINDOW_OPENSECONDARYLOG          0x182FD
#define HID_TASKS_SETAREASINLOWDOSE             0x182FE
#define HID_MACRO_FKEYRUN1                      0x18301
#define HID_MACRO_FKEYRUN2                      0x18302
#define HID_MACRO_FKEYRUN3                      0x18303
#define HID_MACRO_FKEYRUN4                      0x18304
#define HID_MACRO_FKEYRUN5                      0x18305
#define HID_MACRO_FKEYRUN6                      0x18306
#define HID_MACRO_FKEYRUN7                      0x18307
#define HID_MACRO_FKEYRUN8                      0x18308
#define HID_MACRO_FKEYRUN9                      0x18309
#define HID_MACRO_FKEYRUN10                     0x1830A
#define HID_SCRIPT_MAPFUNCTIONKEY               0x1830B
#define HID_SCRIPT_LISTFKEYMAPPINGS             0x1830C
#define HID_BEAMSPOT_PARALLELILLUMINATION       0x1830D
#define HID_HELP_LISTDEBUGOUTPUTKEYLETTERS      0x1830E
#define HID_SPECIALIZEDMISC_SETTHRESHOLDFORRIGHT	0x1830F
 
// Prompts (IDP_*) 
 
// Resources (IDR_*) 
#define HIDR_MAINFRAME                          0x20080
#define HIDR_SERIALTYPE                         0x20081
 
// Dialogs (IDD_*) 
#define HIDD_ABOUTBOX                           0x20064
#define HIDD_ASKONE_DIALOG                      0x20084
#define HIDD_IMAGELEVEL                         0x20085
#define HIDD_BUFFERCONTROL                      0x20086
#define HIDD_FILEPROPERTIES                     0x20087
#define HIDD_BUFFERSTATUS                       0x20088
#define HIDD_TILTCONTROL                        0x20089
#define HIDD_CAMERASETUP                        0x2008A
#define HIDD_ALIGNFOCUS                         0x2008B
#define HIDD_MONTAGESETUP                       0x2008C
#define HIDD_MONTAGECONTROL                     0x2008D
#define HIDD_LOGWINDOW                          0x2008E
#define HIDD_MACRO                              0x20090
#define HIDD_MACROCONTROL                       0x20091
#define HIDD_CAMERA_MACRO                       0x20096
#define HIDD_SCOPESTATUS                        0x20097
#define HIDD_TILTSERIES                         0x20098
#define HIDD_TSRESUME                           0x20099
#define HIDD_TSBACKUP                           0x2009A
#define HIDD_LOWDOSE                            0x2009C
#define HIDD_SCREENMETER                        0x2009D
#define HIDD_FILTERCONTROL                      0x200A0
#define HIDD_GAINREFERENCE                      0x200A2
#define HIDD_NAVIGATOR                          0x200A3
#define HIDD_DUMMYDLG                           0x200A5
#define HIDD_DOSEMETER                          0x200A6
#define HIDD_TSEXTRAFILE                        0x200AD
#define HIDD_REFPOLICY                          0x200AE
#define HIDD_MACROTOOLBAR                       0x200B3
#define HIDD_TSPOLICIES                         0x200B4
#define HIDD_NAVACQUIRE                         0x200B5
#define HIDD_NAVIMPORT                          0x200B7
#define HIDD_COOKSETUP                          0x200B8
#define HIDD_AUTOCENSETUP                       0x200B9
#define HIDD_READFILEDLG                        0x200BD
#define HIDD_TSRANGE                            0x200C1
#define HIDD_TSSETANGLE                         0x200C2
#define HIDD_NAVFILETYPE                        0x200C4
#define HIDD_STATEDLG                           0x200C5
#define HIDD_NAVROTALIGN                        0x200CC
#define HIDD_TSVARIATIONS                       0x200CD
#define HIDD_NCMIR4K                            0x200D1
#define HIDD_8KDialog                           0x200D3
#define HIDD_STEMCONTROL                        0x200D4
#define HIDD_DETOOLDLG                          0x200D5
#define HIDD_NCMIRDLG2                          0x200D6
#define HIDD_NCMIRDLG3                          0x200D7
#define HIDD_NCMIRDLG4                          0x200D8
#define HIDD_NCMIRDLG5                          0x200D9
#define HIDD_NAVBACKLASH                        0x200DA
#define HIDD_FALCON_FRAMES                      0x200DB
#define HIDD_K2_SAVE_OPTIONS                    0x200DC
#define HIDD_STAGEMOVETOOL                      0x200DD
#define HIDD_FRAMEALIGN                         0x200DE
#define HIDD_REMOTE_CONTROL                     0x200DF
#define HIDD_THREE_CHOICE_BOX                   0x200E0
#define HIDD_MULTI_SHOT_SETUP                   0x200E1
#define HIDD_DE_REFERENCE                       0x200E2
#define HIDD_ONELINESCRIPT                      0x200E3
#define HIDD_CTFFINDDLG                         0x200E4
#define HIDD_TSDOSESYM                          0x200E5
#define HIDD_DRIFTWAITSETUP                     0x200E6
#define HIDD_SCREENSHOT                         0x200E7
#define HIDD_VPP_EXPOSE_SETUP                   0x200E8
#define HIDD_HOLE_FINDER                        0x200E9
#define HIDD_MULTI_COMBINER                     0x200EA
#define HIDD_MACROSELECTER                      0x200F9
#define HIDD_SHIFT_TO_MARKER                    0x200FE
#define HIDD_DIALOG1                            0x20100
#define HIDD_Z_BY_G_SETUP                       0x20100
#define HIDD_RADIO_CHOICE                       0x20103
#define HIDD_NAVREALIGN                         0x20105
#define HIDD_MANAGE_DEWARS                      0x20107
#define HIDD_NAVACQ_HOLE_FINDER                 0x2010F
#define HIDD_COMA_VS_IS_CAL                     0x20112
#define HIDD_AUTOCONTOUR                        0x20114
#define HIDD_STEP_AND_ADJUST_IS                 0x20117
#define HIDD_MULTI_GRID                         0x2011C
#define HIDD_MULGRID_SETTINGS                   0x2011F
#define HIDD_TASK_AREA_OPTIONS                  0x20121
#define HIDD_CTF_ACQ_PARAMS                     0x20123
#define HIDD_MANYCHOICEBOX                      0x20126
 
// Frame Controls (IDW_*) 
// This is a part of the Microsoft Foundation Classes C++ library.
// Copyright (C) Microsoft Corporation
// All rights reserved.
//
// This source code is only intended as a supplement to the
// Microsoft Foundation Classes Reference and related
// electronic documentation provided with the library.
// See these sources for detailed information regarding the
// Microsoft Foundation Classes product.

#ifndef __AFX_HH_H__
#define __AFX_HH_H__

#pragma once

#ifdef _AFX_MINREBUILD
#pragma component(minrebuild, off)
#endif

// Non-Client HitTest help IDs
#define HID_HT_NOWHERE                          0x40000
#define HID_HT_CAPTION                          0x40002
#define HID_HT_HSCROLL                          0x40006
#define HID_HT_VSCROLL                          0x40007
#define HID_HT_MINBUTTON                        0x40008
#define HID_HT_MAXBUTTON                        0x40009
#define HID_HT_SIZE                             0x40012 // alias: ID_HT_BORDER
#define HID_HT_OBJECT							0x40013
#define HID_HT_CLOSE							0x40014
#define HID_HT_HELP								0x40015

// WM_SYSCOMMAND help IDs
#define HID_SC_SIZE                             0x1EF00
#define HID_SC_MOVE                             0x1EF01
#define HID_SC_MINIMIZE                         0x1EF02
#define HID_SC_MAXIMIZE                         0x1EF03
#define HID_SC_NEXTWINDOW                       0x1EF04
#define HID_SC_PREVWINDOW                       0x1EF05
#define HID_SC_CLOSE                            0x1EF06
#define HID_SC_RESTORE                          0x1EF12
#define HID_SC_TASKLIST                         0x1EF13

// File MRU and aliases
#define HID_FILE_MRU_FILE1                      0x1E11F

// Window menu list
#define HID_WINDOW_ALL                          0x1EF1F

// OLE menu and aliases
#define HID_OLE_VERB_1                          0x1E21F

// Commands (HID_*) 
#define HID_FILE_NEW                            0x1E100
#define HID_FILE_OPEN                           0x1E101
#define HID_FILE_CLOSE                          0x1E102
#define HID_FILE_SAVE                           0x1E103
#define HID_FILE_SAVE_AS                        0x1E104
#define HID_FILE_PAGE_SETUP                     0x1E105
#define HID_FILE_PRINT_SETUP                    0x1E106
#define HID_FILE_PRINT                          0x1E107
#define HID_FILE_PRINT_DIRECT                   0x1E108
#define HID_FILE_PRINT_PREVIEW                  0x1E109
#define HID_FILE_UPDATE                         0x1E10A
#define HID_FILE_SAVE_COPY_AS                   0x1E10B
#define HID_FILE_SEND_MAIL                      0x1E10C
#define HID_EDIT_CLEAR                          0x1E120
#define HID_EDIT_CLEAR_ALL                      0x1E121
#define HID_EDIT_COPY                           0x1E122
#define HID_EDIT_CUT                            0x1E123
#define HID_EDIT_FIND                           0x1E124
#define HID_EDIT_PASTE                          0x1E125
#define HID_EDIT_PASTE_LINK                     0x1E126
#define HID_EDIT_PASTE_SPECIAL                  0x1E127
#define HID_EDIT_REPEAT                         0x1E128
#define HID_EDIT_REPLACE                        0x1E129
#define HID_EDIT_SELECT_ALL                     0x1E12A
#define HID_EDIT_UNDO                           0x1E12B
#define HID_EDIT_REDO                           0x1E12C
#define HID_WINDOW_NEW                          0x1E130
#define HID_WINDOW_ARRANGE                      0x1E131
#define HID_WINDOW_CASCADE                      0x1E132
#define HID_WINDOW_TILE_HORZ                    0x1E133
#define HID_WINDOW_TILE_VERT                    0x1E134
#define HID_WINDOW_SPLIT                        0x1E135
#define HID_APP_ABOUT                           0x1E140
#define HID_APP_EXIT                            0x1E141
#define HID_HELP_INDEX                          0x1E142
#define HID_HELP_FINDER                         0x1E143
#define HID_HELP_USING                          0x1E144
#define HID_CONTEXT_HELP                        0x1E145
#define HID_NEXT_PANE                           0x1E150
#define HID_PREV_PANE                           0x1E151
#define HID_FORMAT_FONT                         0x1E160
#define HID_OLE_INSERT_NEW                      0x1E200
#define HID_OLE_EDIT_LINKS                      0x1E201
#define HID_OLE_EDIT_CONVERT                    0x1E202
#define HID_OLE_EDIT_CHANGE_ICON                0x1E203
#define HID_OLE_EDIT_PROPERTIES                 0x1E204
#define HID_VIEW_TOOLBAR                        0x1E800
#define HID_VIEW_STATUS_BAR                     0x1E801
#define HID_RECORD_FIRST                        0x1E900
#define HID_RECORD_LAST                         0x1E901
#define HID_RECORD_NEXT                         0x1E902
#define HID_RECORD_PREV                         0x1E903
#define HID_WIZBACK                             0x13023
#define HID_WIZNEXT                             0x13024
#define HID_WIZFINISH                           0x13025

// Dialogs (AFX_HIDD_*)
#define AFX_HIDD_FILEOPEN                       0x27004
#define AFX_HIDD_FILESAVE                       0x27005
#define AFX_HIDD_FONT                           0x27006
#define AFX_HIDD_COLOR                          0x27007
#define AFX_HIDD_PRINT                          0x27008
#define AFX_HIDD_PRINTSETUP                     0x27009
#define AFX_HIDD_FIND                           0x2700A
#define AFX_HIDD_REPLACE                        0x2700B
#define AFX_HIDD_NEWTYPEDLG                     0x27801
#define AFX_HIDD_PRINTDLG                       0x27802
#define AFX_HIDD_PREVIEW_TOOLBAR                0x27803
#define AFX_HIDD_PREVIEW_SHORTTOOLBAR           0x2780B
#define AFX_HIDD_INSERTOBJECT                   0x27804
#define AFX_HIDD_CHANGEICON                     0x27805
#define AFX_HIDD_CONVERT                        0x27806
#define AFX_HIDD_PASTESPECIAL                   0x27807
#define AFX_HIDD_EDITLINKS                      0x27808
#define AFX_HIDD_FILEBROWSE                     0x27809
#define AFX_HIDD_BUSY                           0x2780A
#define AFX_HIDD_OBJECTPROPERTIES               0x2780C
#define AFX_HIDD_CHANGESOURCE                   0x2780D

// Prompts/Errors (AFX_HIDP_*)
#define AFX_HIDP_NO_ERROR_AVAILABLE             0x3F020
#define AFX_HIDP_INVALID_FILENAME               0x3F100
#define AFX_HIDP_FAILED_TO_OPEN_DOC             0x3F101
#define AFX_HIDP_FAILED_TO_SAVE_DOC             0x3F102
#define AFX_HIDP_ASK_TO_SAVE                    0x3F103
#define AFX_HIDP_FAILED_TO_CREATE_DOC           0x3F104
#define AFX_HIDP_FILE_TOO_LARGE                 0x3F105
#define AFX_HIDP_FAILED_TO_START_PRINT          0x3F106
#define AFX_HIDP_FAILED_TO_LAUNCH_HELP          0x3F107
#define AFX_HIDP_INTERNAL_FAILURE               0x3F108
#define AFX_HIDP_COMMAND_FAILURE                0x3F109
#define AFX_HIDP_FAILED_MEMORY_ALLOC            0x3F10A
#define AFX_HIDP_UNREG_DONE                     0x3F10B
#define AFX_HIDP_UNREG_FAILURE                  0x3F10C
#define AFX_HIDP_DLL_LOAD_FAILED                0x3F10D
#define AFX_HIDP_DLL_BAD_VERSION                0x3F10E
#define AFX_HIDP_PARSE_INT                      0x3F110
#define AFX_HIDP_PARSE_REAL                     0x3F111
#define AFX_HIDP_PARSE_INT_RANGE                0x3F112
#define AFX_HIDP_PARSE_REAL_RANGE               0x3F113
#define AFX_HIDP_PARSE_STRING_SIZE              0x3F114
#define AFX_HIDP_PARSE_RADIO_BUTTON             0x3F115
#define AFX_HIDP_PARSE_BYTE                     0x3F116
#define AFX_HIDP_PARSE_UINT                     0x3F117
#define AFX_HIDP_PARSE_DATETIME                 0x3F118
#define AFX_HIDP_PARSE_CURRENCY                 0x3F119
#define AFX_HIDP_FAILED_INVALID_FORMAT          0x3F120
#define AFX_HIDP_FAILED_INVALID_PATH            0x3F121
#define AFX_HIDP_FAILED_DISK_FULL               0x3F122
#define AFX_HIDP_FAILED_ACCESS_READ             0x3F123
#define AFX_HIDP_FAILED_ACCESS_WRITE            0x3F124
#define AFX_HIDP_FAILED_IO_ERROR_READ           0x3F125
#define AFX_HIDP_FAILED_IO_ERROR_WRITE          0x3F126
#define AFX_HIDP_STATIC_OBJECT                  0x3F180
#define AFX_HIDP_FAILED_TO_CONNECT              0x3F181
#define AFX_HIDP_SERVER_BUSY                    0x3F182
#define AFX_HIDP_BAD_VERB                       0x3F183
#define AFX_HIDP_FAILED_TO_NOTIFY               0x3F185
#define AFX_HIDP_FAILED_TO_LAUNCH               0x3F186
#define AFX_HIDP_ASK_TO_UPDATE                  0x3F187
#define AFX_HIDP_FAILED_TO_UPDATE               0x3F188
#define AFX_HIDP_FAILED_TO_REGISTER             0x3F189
#define AFX_HIDP_FAILED_TO_AUTO_REGISTER        0x3F18A
#define AFX_HIDP_FAILED_TO_CONVERT              0x3F18B
#define AFX_HIDP_GET_NOT_SUPPORTED              0x3F18C
#define AFX_HIDP_SET_NOT_SUPPORTED              0x3F18D
#define AFX_HIDP_ASK_TO_DISCARD                 0x3F18E
#define AFX_HIDP_FAILED_TO_CREATE               0x3F18F
#define AFX_HIDP_FAILED_MAPI_LOAD               0x3F190
#define AFX_HIDP_INVALID_MAPI_DLL               0x3F191
#define AFX_HIDP_FAILED_MAPI_SEND               0x3F192
#define AFX_HIDP_FILE_NONE                      0x3F1A0
#define AFX_HIDP_FILE_GENERIC                   0x3F1A1
#define AFX_HIDP_FILE_NOT_FOUND                 0x3F1A2
#define AFX_HIDP_FILE_BAD_PATH                  0x3F1A3
#define AFX_HIDP_FILE_TOO_MANY_OPEN             0x3F1A4
#define AFX_HIDP_FILE_ACCESS_DENIED             0x3F1A5
#define AFX_HIDP_FILE_INVALID_FILE              0x3F1A6
#define AFX_HIDP_FILE_REMOVE_CURRENT            0x3F1A7
#define AFX_HIDP_FILE_DIR_FULL                  0x3F1A8
#define AFX_HIDP_FILE_BAD_SEEK                  0x3F1A9
#define AFX_HIDP_FILE_HARD_IO                   0x3F1AA
#define AFX_HIDP_FILE_SHARING                   0x3F1AB
#define AFX_HIDP_FILE_LOCKING                   0x3F1AC
#define AFX_HIDP_FILE_DISKFULL                  0x3F1AD
#define AFX_HIDP_FILE_EOF                       0x3F1AE
#define AFX_HIDP_ARCH_NONE                      0x3F1B0
#define AFX_HIDP_ARCH_GENERIC                   0x3F1B1
#define AFX_HIDP_ARCH_READONLY                  0x3F1B2
#define AFX_HIDP_ARCH_ENDOFFILE                 0x3F1B3
#define AFX_HIDP_ARCH_WRITEONLY                 0x3F1B4
#define AFX_HIDP_ARCH_BADINDEX                  0x3F1B5
#define AFX_HIDP_ARCH_BADCLASS                  0x3F1B6
#define AFX_HIDP_ARCH_BADSCHEMA                 0x3F1B7
#define AFX_HIDP_SQL_CONNECT_FAIL               0x3F281
#define AFX_HIDP_SQL_RECORDSET_FORWARD_ONLY     0x3F282
#define AFX_HIDP_SQL_EMPTY_COLUMN_LIST          0x3F283
#define AFX_HIDP_SQL_FIELD_SCHEMA_MISMATCH      0x3F284
#define AFX_HIDP_SQL_ILLEGAL_MODE               0x3F285
#define AFX_HIDP_SQL_MULTIPLE_ROWS_AFFECTED     0x3F286
#define AFX_HIDP_SQL_NO_CURRENT_RECORD          0x3F287
#define AFX_HIDP_SQL_NO_ROWS_AFFECTED           0x3F288
#define AFX_HIDP_SQL_RECORDSET_READONLY         0x3F289
#define AFX_HIDP_SQL_SQL_NO_TOTAL               0x3F28A
#define AFX_HIDP_SQL_ODBC_LOAD_FAILED           0x3F28B
#define AFX_HIDP_SQL_DYNASET_NOT_SUPPORTED      0x3F28C
#define AFX_HIDP_SQL_SNAPSHOT_NOT_SUPPORTED     0x3F28D
#define AFX_HIDP_SQL_API_CONFORMANCE            0x3F28E
#define AFX_HIDP_SQL_SQL_CONFORMANCE            0x3F28F
#define AFX_HIDP_SQL_NO_DATA_FOUND              0x3F290
#define AFX_HIDP_SQL_ROW_UPDATE_NOT_SUPPORTED   0x3F291
#define AFX_HIDP_SQL_ODBC_V2_REQUIRED           0x3F292
#define AFX_HIDP_SQL_NO_POSITIONED_UPDATES      0x3F293
#define AFX_HIDP_SQL_LOCK_MODE_NOT_SUPPORTED    0x3F294
#define AFX_HIDP_SQL_DATA_TRUNCATED             0x3F295
#define AFX_HIDP_SQL_ROW_FETCH                  0x3F296
#define AFX_HIDP_SQL_INCORRECT_ODBC             0x3F297
#define AFX_HIDP_SQL_UPDATE_DELETE_FAILED       0x3F298
#define AFX_HIDP_SQL_DYNAMIC_CURSOR_NOT_SUPPORTED	0x3F299
#define AFX_HIDP_SQL_FIELD_NOT_FOUND            0x3F29A
#define AFX_HIDP_SQL_BOOKMARKS_NOT_SUPPORTED    0x3F29B
#define AFX_HIDP_SQL_BOOKMARKS_NOT_ENABLED      0x3F29C
#define AFX_HIDP_DAO_ENGINE_INITIALIZATION      0x3F2B0
#define AFX_HIDP_DAO_DFX_BIND                   0x3F2B1
#define AFX_HIDP_DAO_OBJECT_NOT_OPEN            0x3F2B2
#define AFX_HIDP_DAO_ROWTOOSHORT                0x3F2B3
#define AFX_HIDP_DAO_BADBINDINFO                0x3F2B4
#define AFX_HIDP_DAO_COLUMNUNAVAILABLE          0x3F2B5

// Frame Controls (AFX_HIDW_*)
#define AFX_HIDW_TOOLBAR                        0x5E800
#define AFX_HIDW_STATUS_BAR                     0x5E801
#define AFX_HIDW_PREVIEW_BAR                    0x5E802
#define AFX_HIDW_RESIZE_BAR                     0x5E803
#define AFX_HIDW_DOCKBAR_TOP                    0x5E81B
#define AFX_HIDW_DOCKBAR_LEFT                   0x5E81C
#define AFX_HIDW_DOCKBAR_RIGHT                  0x5E81D
#define AFX_HIDW_DOCKBAR_BOTTOM                 0x5E81E
#define AFX_HIDW_DOCKBAR_FLOAT                  0x5E81F

/////////////////////////////////////////////////////////////////////////////

#ifdef _AFX_MINREBUILD
#pragma component(minrebuild, on)
#endif

#endif // __AFX_HH_H__
