#define MAC_DIFF_NAME_2SO1S MAC_DIFF_NAME
#define MAC_DIFF_NAME_O1SO1D MAC_DIFF_NAME
#define MAC_SAME_FUNC_1DO1S MAC_SAME_FUNC
#define MAC_SAME_FUNC_1DO5D MAC_SAME_FUNC
#define MAC_SAME_FUNC_1S1DO4D MAC_SAME_FUNC
#define MAC_SAME_FUNC_1SO1S MAC_SAME_FUNC
#define MAC_SAME_FUNC_1SO2D MAC_SAME_FUNC
#define MAC_SAME_FUNC_2DO5D MAC_SAME_FUNC
#define MAC_SAME_FUNC_2SO1S MAC_SAME_FUNC
#define MAC_SAME_FUNC_3DO2D MAC_SAME_FUNC
#define MAC_SAME_FUNC_NOARG MAC_SAME_FUNC
#define MAC_SAME_FUNC_O1SO1D MAC_SAME_FUNC
#define MAC_SAME_FUNC_O5D MAC_SAME_FUNC
#define MAC_SAME_NAME_1DO1S MAC_SAME_NAME
#define MAC_SAME_NAME_1DO5D MAC_SAME_NAME
#define MAC_SAME_NAME_1S1DO4D MAC_SAME_NAME
#define MAC_SAME_NAME_1SO1S MAC_SAME_NAME
#define MAC_SAME_NAME_1SO2D MAC_SAME_NAME
#define MAC_SAME_NAME_2DO5D MAC_SAME_NAME
#define MAC_SAME_NAME_2SO1S MAC_SAME_NAME
#define MAC_SAME_NAME_3DO2D MAC_SAME_NAME
#define MAC_SAME_NAME_NOARG MAC_SAME_NAME
#define MAC_SAME_NAME_O1DO1S MAC_SAME_NAME
#define MAC_SAME_NAME_O1SO1D MAC_SAME_NAME
#define MAC_SAME_NAME_O5D MAC_SAME_NAME
#define MAC_SAME_NAME_GEN(a, b, c, d, e) MAC_SAME_NAME(a, b, c, d)
#define MAC_DIFF_NAME_GEN(a, b, c, d, e, f) MAC_DIFF_NAME(a, b, c, d, e)
#define MAC_SAME_FUNC_GEN(a, b, c, d, e, f) MAC_SAME_FUNC(a, b, c, d, e)

