//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SerialEM.rc
//
#define IDC_BROWSE                      3
#define ID_TASK_TIMER                   7
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_SERIALTYPE                  129
#define IDD_ASKONE_DIALOG               132
#define IDD_IMAGELEVEL                  133
#define IDD_BUFFERCONTROL               134
#define IDD_FILEPROPERTIES              135
#define IDD_BUFFERSTATUS                136
#define IDD_TILTCONTROL                 137
#define IDD_CAMERASETUP                 138
#define IDD_ALIGNFOCUS                  139
#define IDD_MONTAGESETUP                140
#define IDD_MONTAGECONTROL              141
#define IDD_LOGWINDOW                   142
#define IDC_CURSOR1                     143
#define IDD_MACRO                       144
#define IDD_MACROCONTROL                145
#define IDD_CAMERA_MACRO                150
#define IDD_SCOPESTATUS                 151
#define IDD_TILTSERIES                  152
#define IDD_TSRESUME                    153
#define IDD_TSBACKUP                    154
#define IDB_BITMAP1                     155
#define IDD_LOWDOSE                     156
#define IDD_SCREENMETER                 157
#define IDC_CURSOR2                     158
#define IDD_FILTERCONTROL               160
#define IDD_GAINREFERENCE               162
#define IDD_NAVIGATOR                   163
#define IDD_DUMMYDLG                    165
#define IDD_DOSEMETER                   166
#define IDD_TSEXTRAFILE                 173
#define IDD_REFPOLICY                   174
#define IDD_MACROTOOLBAR                179
#define IDD_TSPOLICIES                  180
#define IDD_NAVACQUIRE                  181
#define IDD_NAVIMPORT                   183
#define IDD_COOKSETUP                   184
#define IDD_AUTOCENSETUP                185
#define IDD_READFILEDLG                 189
#define IDD_DirectElectronDialog        190
#define IDD_TSRANGE                     193
#define IDD_TSSETANGLE                  194
#define IDD_NAVFILETYPE                 196
#define IDD_STATEDLG                    197
#define IDD_NAVROTALIGN                 204
#define IDD_TSVARIATIONS                205
#define IDD_NCMIR4K                     209
#define IDD_8KDialog                    211
#define IDD_STEMCONTROL                 212
#define IDD_DETOOLDLG                   213
#define IDD_NCMIRDLG2                   214
#define IDD_NCMIRDLG3                   215
#define IDD_NCMIRDLG4                   216
#define IDD_NCMIRDLG5                   217
#define IDD_NAVBACKLASH                 218
#define IDD_FALCON_FRAMES               219
#define IDD_K2_SAVE_OPTIONS             220
#define IDD_STAGEMOVETOOL               221
#define IDD_FRAMEALIGN                  222
#define IDD_REMOTE_CONTROL              223
#define IDD_THREE_CHOICE_BOX            224
#define IDD_MULTI_SHOT_SETUP            225
#define IDD_DE_REFERENCE                226
#define IDD_ONELINESCRIPT               227
#define IDC_EDITXSIZE                   1000
#define IDC_EDITYSIZE                   1002
#define IDC_EDITYOVERLAP                1003
#define IDC_ASKONE_EDIT                 1005
#define IDC_ASKONE_TEXT                 1006
#define IDC_BRIGHTNESS                  1008
#define IDC_CONTRAST                    1009
#define IDC_WHITE                       1010
#define IDC_BLACK                       1011
#define IDC_TRUNCATION                  1012
#define IDC_AREAFRACTION                1013
#define IDC_BUTOPEN                     1014
#define IDC_BCOPYA                      1015
#define IDC_BUTMORE                     1016
#define IDC_SPINCOPY                    1017
#define IDC_BCOPYB                      1018
#define IDC_BCOPYC                      1019
#define IDC_BCOPYD                      1020
#define IDC_BSAVEACTIVE                 1022
#define IDC_BSAVEA                      1023
#define IDC_BSTOP                       1024
#define IDC_BSTART                      1025
#define IDC_SPINROLL                    1026
#define IDC_ROLLBUF                     1027
#define IDC_COPYONSAVE                  1028
#define IDC_READBUF                     1029
#define IDC_SPINREAD                    1030
#define IDC_CONFIRMDESTROY              1031
#define IDC_ALIGNONSAVE                 1032
#define IDC_CORRECTDRIFT                1033
#define IDC_AUTOZOOM                    1034
#define IDC_RBYTE                       1036
#define IDC_RINTEGERS                   1037
#define IDC_MAXSECTSTEXT                1038
#define IDC_BEGENEROUS                  1039
#define IDC_MAXSECTSEDIT                1040
#define IDC_TRUNCGROUP                  1041
#define IDC_TRUNCBLACKTEXT              1042
#define IDC_TRUNCBLACKEDIT              1043
#define IDC_TRUNCWHITEEDIT              1045
#define IDC_TILTANGLE                   1049
#define IDC_STAGEPOS                    1050
#define IDC_MAGNIFICATION               1051
#define IDC_TRUNCWHITETEXT              1052
#define IDC_BCOPYANY                    1053
#define IDC_EDITZOOM                    1054
#define IDC_SPINZOOM                    1055
#define IDC_OTHERBUF1                   1056
#define IDC_SPINTARGET                  1057
#define IDC_DISPLAYEDBUF                1058
#define IDC_SIZETEXT                    1059
#define IDC_OTHERBUF2                   1060
#define IDC_OTHERBUF3                   1061
#define IDC_STAGETEXT                   1062
#define IDC_TILTTEXT                    1063
#define IDC_TILT_UP                     1064
#define IDC_TILT_DOWN                   1065
#define IDC_TILT_TO                     1066
#define IDC_TILT_INCREMENT              1067
#define IDC_COSINE_TILT                 1068
#define IDC_TILT_TEXT                   1069
#define IDC_RVIEW                       1070
#define IDC_RFOCUS                      1071
#define IDC_RTRIAL                      1072
#define IDC_RRECORD                     1073
#define IDC_RPREVIEW                    1074
#define IDC_BIGMODETEXT                 1075
#define IDC_RSINGLE                     1076
#define IDC_RCONTINUOUS                 1077
#define IDC_RUNPROCESSED                1078
#define IDC_RDARKSUBTRACT               1079
#define IDC_RGAINNORMALIZED             1080
#define IDC_RBOOSTMAG3                  1081
#define IDC_RBOOSTMAG4                  1082
#define IDC_EDITEXPOSURE                1087
#define IDC_EDITSETTLING                1088
#define IDC_RBEAMONLY                   1089
#define IDC_RFILMONLY                   1090
#define IDC_RSHUTTERCOMBO               1091
#define IDC_DARKALWAYS                  1092
#define IDC_DARKNEXT                    1093
#define IDC_BUTFULL                     1094
#define IDC_EDITTOP                     1095
#define IDC_EDITLEFT                    1096
#define IDC_EDITRIGHT                   1097
#define IDC_EDITBOTTOM                  1098
#define IDC_BUTWIDEHALF                 1099
#define IDC_BUTWIDEQUARTER              1100
#define IDC_BUTQUARTER                  1101
#define IDC_BUTHALF                     1102
#define IDC_DRIFTTEXT1                  1104
#define IDC_DRIFTTEXT2                  1105
#define IDC_STATBOX                     1107
#define IDC_BLANKING                    1108
#define IDC_MINIMUM_DRIFT               1109
#define IDC_BUTALIGN                    1110
#define IDC_BUTCLEARALIGN               1111
#define IDC_BUTRESETSHIFT               1112
#define IDC_STATMAG                     1113
#define IDC_STATBIN                     1114
#define IDC_SPINMAG                     1115
#define IDC_SPINBIN                     1116
#define IDC_STATPIXEL                   1117
#define IDC_STATTOTALAREA               1118
#define IDC_SPINXFRAMES                 1119
#define IDC_SPINYFRAMES                 1120
#define IDC_EDITXOVERLAP                1121
#define IDC_STATNPIECE                  1122
#define IDC_STATICY1                    1123
#define IDC_STATICY2                    1124
#define IDC_STATPIECESIZE               1125
#define IDC_STATOVERLAP                 1126
#define IDC_BTRIAL                      1127
#define IDC_STATICY3                    1128
#define IDC_STATTOTALPIXELS             1129
#define IDC_SPINZ                       1130
#define IDC_STATCURRENTZ                1131
#define IDC_LOGEDIT                     1132
#define IDC_RADIONONE                   1133
#define IDC_RADIOFOCUS                  1134
#define IDC_EDITMACRO                   1135
#define IDC_RADIORECORD                 1136
#define IDC_RADIOTRIAL                  1137
#define IDC_LIMIT_WHITELEVEL            1138
#define IDC_LIMIT_MONTERROR             1139
#define IDC_LIMIT_RUNS                  1140
#define IDC_LIMIT_IMAGESHIFT            1141
#define IDC_EDIT_TILTUP                 1142
#define IDC_EDIT_TILTDOWN               1143
#define IDC_EDIT_WHITELEVEL             1144
#define IDC_EDIT_MONTERROR              1145
#define IDC_EDIT_RUNS                   1146
#define IDC_EDIT_IMAGESHIFT             1147
#define IDC_BUTMACRO1                   1151
#define IDC_BUTMACRO2                   1152
#define IDC_SPINMACRO2                  1153
#define IDC_BUTSTOP                     1155
#define IDC_BUTMACRO3                   1156
#define IDC_SPINMACRO3                  1158
#define IDC_STATTOPLINE                 1159
#define IDC_STATBLACK                   1160
#define IDC_STATWHITE                   1161
#define IDC_STATOPTIONS                 1162
#define IDC_STATGROUP                   1163
#define IDC_STATZOOM                    1164
#define IDC_STATBRI                     1165
#define IDC_STATCON                     1166
#define IDC_SPINMACRO1                  1167
#define IDC_SCREEN_CURRENT              1168
#define IDC_STAGE_X                     1169
#define IDC_STAGE_Y                     1170
#define IDC_IMAGE_SHIFT                 1171
#define IDC_STATDEFOCUS                 1172
#define IDC_RBIN1                       1173
#define IDC_RBIN2                       1174
#define IDC_RBIN3                       1175
#define IDC_RBIN4                       1176
#define IDC_RBIN5                       1177
#define IDC_RBIN6                       1178
#define IDC_RBIN7                       1179
#define IDC_RBIN8                       1180
#define IDC_RBIN9                       1181
#define IDC_RBIN10                      1182
#define IDC_WALKUP                      1183
#define IDC_RESET_REALIGN               1184
#define IDC_OBJECTIVE                   1185
#define IDC_EDITSTARTANGLE              1186
#define IDC_EDITENDANGLE                1187
#define IDC_EDITINCREMENT               1188
#define IDC_COSINEINC                   1189
#define IDC_SPOTSIZE                    1190
#define IDC_STATBINNING                 1191
#define IDC_STATRECORDMAG               1192
#define IDC_LOWMAGTRACK                 1194
#define IDC_STATLOWMAG                  1195
#define IDC_SPINTRACKMAG                1196
#define IDC_RCONSTANTBEAM               1197
#define IDC_RINTENSITYMEAN              1198
#define IDC_RINTENSITYCOSINE            1199
#define IDC_EDITCOUNTS                  1200
#define IDC_REFINEEUCEN                 1201
#define IDC_LEAVEANCHOR                 1202
#define IDC_EDITANCHOR                  1203
#define IDC_USEANCHOR                   1204
#define IDC_STATANCHORBUF               1205
#define IDC_SPINANCHOR                  1206
#define IDC_EDITLIMITIS                 1207
#define IDC_EDITBEAMTILT                1208
#define IDC_EDITCHECKFOCUS              1209
#define IDC_EDIT_ZLP_INTERVAL           1210
#define IDC_EDITREPEATRECORD            1211
#define IDC_REPEATFOCUS                 1212
#define IDC_EDITREPEATFOCUS             1213
#define IDC_EDITMINSEPARATE             1214
#define IDC_EDITMINCOMBINED             1215
#define IDC_EDITMAXTILTFITYZ            1216
#define IDC_EDITMAXTILTFITX             1217
#define IDC_EDITTILTDELAY               1218
#define IDC_STATTOTALTILT               1219
#define IDC_STATSTARTAT                 1220
#define IDC_STATBASICINC                1221
#define IDC_STATMAGLABEL                1222
#define IDC_STATBINLABEL                1223
#define IDC_STATWALKBOX                 1224
#define IDC_STATANCHORDEG               1225
#define IDC_EDITFOCUSTARGET             1226
#define IDC_USEAFORREF                  1227
#define IDC_BUTRESUME                   1228
#define IDC_BUTEND                      1229
#define IDC_RFIXED                      1230
#define IDC_RSTEPS14                    1231
#define IDS_STRING1232                  1232
#define IDC_LOADMACRO                   1233
#define IDC_STATFIXZOOM                 1234
#define IDC_SINGLELOOP                  1235
#define IDC_STATSTATUS                  1236
#define IDC_RRESUME                     1237
#define IDC_RSAVERECINA                 1238
#define IDC_RTAKEREC                    1239
#define IDC_RFOCUSREC                   1240
#define IDC_RTRACKFOCUS                 1241
#define IDC_USENEWREF                   1242
#define IDC_LISTZTILT                   1243
#define IDC_ALWAYSFOCUS                 1244
#define IDC_RAMPBEAM                    1245
#define IDC_STATTAPERFTA                1246
#define IDC_STATTAPERDEG                1247
#define IDC_STATCURRENTBOX              1248
#define IDC_STATSHOWBOX                 1249
#define IDC_RSHOWVIEW                   1250
#define IDC_RSHOWRECORD                 1251
#define IDC_RSHOWTRIAL                  1252
#define IDC_RSHOWFOCUS                  1253
#define IDC_BLANKBEAM                   1254
#define IDC_RDEFINETRIAL                1255
#define IDC_RDEFINEFOCUS                1256
#define IDC_RDEFINENONE                 1257
#define IDC_TIEFOCUSTRIAL               1258
#define IDC_EDITPOSITION                1259
#define IDC_STATMAGSPOTC2               1260
#define IDC_LOWDOSEMODE                 1261
#define IDC_STATDEFINEBOX               1262
#define IDC_STATPOSITION                1263
#define IDC_STATMICRON                  1264
#define IDC_STATALIGNBUF                1265
#define IDC_SAVEMACRO                   1266
#define IDC_STATBEAMBOX                 1267
#define IDC_CONTINUOUSUPDATE            1268
#define IDC_CENTERUNSHIFTED             1269
#define IDC_BALANCESHIFTS               1270
#define IDC_BUTSMALLER10                1271
#define IDC_BUTABITLESS                 1272
#define IDC_STATMETER                   1273
#define IDC_SPINRECORDMAG               1274
#define IDC_REPEATRECORD                1275
#define IDC_EDITMAXTILTFITZ             1276
#define IDC_EDITMINQUADXFIT             1277
#define IDC_EDITMINQUADYFIT             1278
#define IDC_EDITTAPERANGLE              1279
#define IDC_UPDATE                      1280
#define IDC_POSTPONE                    1281
#define IDC_SINGLESTEP                  1282
#define IDC_SAVEMACROAS                 1283
#define IDC_RUNMACRO                    1284
#define IDC_DEFOCUS                     1285
#define IDC_SPINCURRENTBUF              1286
#define IDC_EDITXNFRAMES                1287
#define IDC_EDITYNFRAMES                1288
#define IDC_BUTFOCUS                    1289
#define IDC_ADJUSTFOCUS                 1290
#define IDC_EDITZ                       1291
#define IDC_LIMIT_TILTUP                1292
#define IDC_LIMIT_TILTDOWN              1293
#define IDC_SHOW_OVERVIEW               1294
#define IDC_STATTITLE                   1295
#define IDC_STATMORE                    1296
#define IDC_GROUPSHOOT                  1297
#define IDC_EDITALWAYSFOCUS             1298
#define IDC_EDITTAPERCOUNTS             1299
#define IDC_EDITMAXTILTFITY             1300
#define IDC_EDITMINFOCUSRATIO           1301
#define IDC_BUTBIGGER10                 1302
#define IDC_BUTMONTAGE                  1303
#define IDC_BUTFLOAT                    1304
#define IDC_TSGO                        1305
#define IDC_TILT_DELAY                  1306
#define IDC_ALIGNTRACKONLY              1307
#define IDC_STATNEWTRACK                1308
#define IDC_STATPERCENT                 1309
#define IDC_COPYTOVIEW                  1310
#define IDC_COPYTOFOCUS                 1311
#define IDC_COPYTOTRIAL                 1312
#define IDC_COPYTORECORD                1313
#define IDC_RNEXTTILT                   1314
#define IDC_RLOWTRACKFOCUS              1315
#define IDC_BUTHELP                     1316
#define IDC_EDITNEWTRACKDIFF            1317
#define IDC_EDITPREDICTERRORZ           1318
#define IDC_EDITPREDICTERRORXY          1319
#define IDC_SMOOTHED                    1320
#define IDC_EVALMULTIPLE                1321
#define ID_TESTACQUIRE                  1322
#define IDC_BUTFLOATDOCK                1323
#define IDC_STATCAMERA                  1324
#define IDC_BUTCOPYCAMERA               1329
#define IDC_STATCOPYCAMERA              1330
#define IDC_EFTEMMODE                   1331
#define IDC_AUTOMAG                     1332
#define IDC_STATONOFF                   1333
#define IDC_SLITIN                      1334
#define ID_DELETESETTINGS               1335
#define IDC_EDITWIDTH                   1336
#define IDC_SPINWIDTH                   1337
#define IDC_EDITLOSS                    1338
#define IDC_SPINLOSS                    1339
#define IDC_AUTOCAMERA                  1340
#define IDC_MATCHINTENSITY              1342
#define IDC_MATCHPIXEL                  1343
#define IDC_DOMAGSHIFTS                 1344
#define IDC_STATMAGSHIFT                1345
#define IDC_ZLPALIGNED                  1346
#define IDC_UNBLANK                     1347
#define IDC_STATBLANKED                 1348
#define IDC_EDITTARGET                  1349
#define IDC_EDITFRAMES                  1350
#define IDC_RADIOBIN1                   1351
#define IDC_RADIOBIN2                   1352
#define IDC_STATODDREF                  1353
#define IDC_STATEXISTING                1354
#define IDC_SPINFRAMES                  1355
#define IDC_RTRUNCATE                   1356
#define IDC_RDIVIDE                     1357
#define IDC_RSHIFTDOWN                  1358
#define IDC_STATSAVING16                1359
#define IDC_CHECKAUTOFOCUS              1360
#define IDC_STATTIMESACTUAL             1361
#define IDC_ZEROLOSS                    1362
#define IDC_STATOFFSET                  1363
#define IDC_STATVACUUM                  1364
#define IDC_MOUSESTAGE                  1365
#define IDC_BUTSTAGETHRESH              1366
#define IDC_LIMITINTENSITY              1367
#define IDC_SKIPAUTOFOCUS               1368
#define IDC_RTRACKBEFORE                1369
#define IDC_RTRACKAFTER                 1370
#define IDC_RTRACKBOTH                  1371
#define IDC_PREVIEWBEFOREREF            1372
#define IDC_STATCHECKDEG                1373
#define IDC_STATCHECKEVERY              1374
#define IDC_STATALWAYSFOCUS             1375
#define IDC_EDITFOCUSOFFSET             1376
#define IDC_STATSIZE                    1377
#define IDC_SPINLEFTRIGHT               1378
#define IDC_SPINUPDOWN                  1380
#define IDC_BUTRECENTER                 1381
#define IDC_MOVESTAGE                   1382
#define IDC_STATSCANBIN                 1383
#define IDC_STATOVERVIEWBIN             1385
#define IDC_SHIFT_IN_OVERVIEW           1386
#define IDC_LISTVIEWER                  1388
#define IDC_DRAW_POINTS                 1389
#define IDC_DRAW_POLYGON                1390
#define IDC_DELETEITEM                  1391
#define IDC_ADD_STAGE_POS               1392
#define IDC_ADD_MARKER                  1393
#define IDC_MOVE_ITEM                   1394
#define IDC_GOTO_POINT                  1395
#define IDC_NEW_MAP                     1396
#define IDC_LOAD_MAP                    1397
#define IDC_EDIT_PTLABEL                1398
#define IDC_EDIT_PTNOTE                 1399
#define IDC_GOTO_MARKER                 1400
#define IDC_SAVE_NAV_FILE               1401
#define IDC_STAT_CURRENTREG             1405
#define IDC_CHECK_REGPOINT              1406
#define IDC_STAT_REGPT_NUM              1409
#define IDC_SPIN_REGPT_NUM              1410
#define IDC_CHECKCORNER                 1411
#define IDC_TRANSFORM_PTS               1412
#define IDC_CORNER_MONTAGE              1413
#define IDC_POLYGON_MONTAGE             1414
#define IDC_DRAW_ALL                    1415
#define IDC_DRAW_ONE                    1416
#define IDC_GOTO_XY                     1417
#define IDC_SAVEAS_NAV_FILE             1418
#define IDC_COMBOCOLOR                  1419
#define IDC_CHECK_ACQUIRE               1420
#define IDC_STAT_UMMM                   1421
#define IDC_LIMITTOCURRENT              1422
#define IDC_STATCURRENTCOUNTS           1423
#define IDC_STATTOTALDOSE               1424
#define IDC_STATELECDOSE                1425
#define IDC_IGNORESKIPS                 1426
#define IDC_USEINTENSITYATZERO          1427
#define IDC_ASKINFOLINE                 1428
#define IDC_CENTERONAXIS                1429
#define IDC_TRIMBORDERS                 1430
#define IDC_SPINVIEWBIN                 1431
#define IDC_SPINCURRENT_REG             1432
#define IDC_SPINCOSINEPOWER             1433
#define IDC_SPINSCANBIN                 1434
#define IDC_SAVE_INTENSITY              1436
#define IDC_DRAW_ALL_REG                1437
#define IDC_DRAW_NONE                   1438
#define IDC_REFINE_ZLP                  1439
#define IDC_AUTO_REFINE_ZLP             1440
#define IDC_STATMINUTES                 1441
#define IDC_STATMILLIRAD                1442
#define IDC_STOPONBIGSHIFT              1443
#define IDC_EDITBIGSHIFT                1444
#define IDC_ALIGNTOB                    1445
#define IDC_OFFSET_SLIT                 1446
#define IDC_LDNORMALIZE_BEAM            1447
#define IDC_RESET_BEAM_SHIFT            1448
#define IDC_SET_BEAM_SHIFT              1449
#define IDC_STATBEAMSHIFT               1450
#define IDC_SET_TRIM_FRAC               1451
#define IDC_SET_VIEW_SHIFT              1452
#define IDC_RUNSIGNED                   1453
#define IDC_BUTRESET                    1454
#define IDC_STATCUMDOSE                 1455
#define IDC_BUTUPDATEDOSE               1456
#define IDC_BUTDOSE                     1457
#define IDC_CHECKNORMSPOT               1458
#define IDC_VERY_SLOPPY                 1459
#define IDC_CLOSE_VALVES                1460
#define IDC_MANUAL_TRACKING             1461
#define IDC_STATNANO                    1462
#define IDC_AVERAGEDARK                 1463
#define IDC_EDITAVERAGE                 1464
#define IDC_CENTER_FROM_TRIAL           1465
#define IDC_SPINAVERAGE                 1467
#define IDC_STATAVERAGE                 1468
#define IDC_GR_AVERAGEDARK              1469
#define IDC_GR_EDITAVERAGE              1470
#define IDC_GR_SPINAVERAGE              1471
#define IDC_AVERAGERECREF               1472
#define IDC_MACROHELP                   1473
#define IDC_REMOVEXRAYS                 1474
#define IDC_STATXLM                     1475
#define IDC_STAT_LDAREA                 1476
#define IDC_SPINTOFILE                  1478
#define IDC_STATTOFILE                  1480
#define IDC_TSSAVEVIEW                  1481
#define IDC_SAVEFOCUS                   1482
#define IDC_SAVETRIAL                   1483
#define IDC_SAVEPREVIEW                 1484
#define IDC_STATVIEWNUM                 1485
#define IDC_STATFOCUSNUM                1486
#define IDC_STATTRIALNUM                1487
#define IDC_STATPREVIEWNUM              1488
#define IDC_STATRECORDNUM               1489
#define IDC_SPINVIEW                    1490
#define IDC_SPINFOCUS                   1491
#define IDC_SPINTRIAL                   1492
#define IDC_SPINPREVIEW                 1493
#define IDC_SPINRECORD                  1494
#define IDC_STATEXTRAREC                1497
#define IDC_NOEXTRA                     1498
#define IDC_FOCUSSERIES                 1499
#define IDC_FILTERSERIES                1500
#define IDC_STATINSTRUCT1               1501
#define IDC_STATINSTRUCT2               1502
#define IDC_EDITENTRIES                 1503
#define IDC_TOPREVMACRO                 1504
#define IDC_TONEXTMACRO                 1505
#define IDC_STATNAVFIT2                 1506
#define IDC_STATNAVFIT3                 1507
#define IDC_MINOVLABEL                  1508
#define IDC_MINOVVALUE                  1509
#define IDC_SPINMINOV                   1510
#define IDC_ACQUIRE_REOPEN              1511
#define IDC_STATDEFTARGET               1512
#define IDC_STATFILENAME                1513
#define IDC_STACKRECORD                 1514
#define IDC_STATKBPIMAGE                1515
#define IDC_GRPEXTRAREC                 1516
#define IDC_STATEXTRAINSTR1             1517
#define IDC_APPLYISOFFSET               1518
#define IDC_CHECKROTATE                 1519
#define IDC_REALIGNTOITEM               1520
#define IDC_RSHOWSEARCH                 1521
#define IDC_SEARCH                      1522
#define IDC_SPINBINSIZE                 1523
#define IDC_CHECK_IGNORE_HIGH           1524
#define IDC_DELETEBUF                   1525
#define IDC_STATMEMORY                  1526
#define IDC_STATVERSION                 1527
#define IDC_STATTAG                     1528
#define IDC_BUTRESETDEFOCUS             1529
#define IDC_STATNAVFIT1                 1530
#define IDC_CHECK_PREFER_BIN2           1532
#define IDC_STAT_DMGROUP                1533
#define IDC_RADIO_ASK_IF_NEWER          1534
#define IDC_RADIO_ASK_ALWAYS            1535
#define IDC_RADIO_ASK_NEVER             1536
#define IDC_CHECK_SETEXPOSURE           1537
#define IDC_EDIT_NEWEXPOSURE            1538
#define IDC_EDIT_NEWDRIFT               1539
#define IDC_SPIN_NEWSPOT                1541
#define IDC_STAT_NEWSPOT                1542
#define IDC_EDIT_DELTAC2                1543
#define IDC_CHECK_SETSPOT               1544
#define IDC_EXPOSURE_DOSE               1545
#define IDC_STATSAVETYPE                1546
#define IDC_EXTENDEDGROUP               1547
#define IDC_TILTTERM                    1549
#define IDC_TILTCONT                    1550
#define IDC_LDDIMREPEAT                 1551
#define IDC_LDDIMCONT                   1552
#define IDC_LDDIMTERM                   1553
#define IDC_LDLOSSTERM                  1554
#define IDC_LDLOSSCONT                  1555
#define IDC_LDLOSSREPEAT                1556
#define IDC_NA_REALIGNITEM              1557
#define IDC_NA_FINE_EUCEN               1558
#define IDC_NA_AUTOFOCUS                1559
#define IDC_NA_ACQUIREMAP               1560
#define IDC_NA_JUSTACQUIRE              1561
#define IDC_NA_RUNMACRO                 1562
#define IDC_SPIN_NAV_MACNUM             1563
#define IDC_STAT_NAVMACNUM              1564
#define IDC_NA_RESTORE_STATE            1565
#define IDC_NA_ROUGH_EUCEN              1566
#define IDC_NA_CLOSE_VALVES             1567
#define IDC_STAT_NA_MACRONAME           1568
#define IDC_ERRORMESSAGE                1569
#define IDC_ERRORTERM                   1570
#define IDC_SPINVIEWDEFOCUS             1571
#define IDC_STATVIEWDEFOCUS             1572
#define IDC_STATVIEWDEFLABEL            1573
#define IDC_CHECK_SKIP_OUTSIDE          1574
#define IDC_EDIT_SKIP_OUTSIDE           1575
#define IDC_FOCUS_AFTER_STAGE           1576
#define IDC_XFORMCOMBO                  1577
#define IDC_EDITSECTION                 1578
#define IDC_STATSECTION                 1579
#define IDC_EDIT_STAGEX                 1581
#define IDC_EDIT_STAGEY                 1582
#define IDC_STATCAMLABEL                1583
#define IDC_SPIN_REGNUM                 1584
#define IDC_STAT_REGNUM                 1585
#define IDC_CROSSHAIRS                  1586
#define IDC_STATLISTHEADER              1587
#define IDC_CHECKOFFERMAP               1588
#define IDC_SCALEBAR                    1589
#define IDC_SET_TRACK_STATE             1590
#define IDC_COOKMAG                     1591
#define IDC_COOKSPOT                    1592
#define IDC_COOKINTENSITY               1593
#define IDC_ALIGNCOOKED                 1594
#define IDC_EDITCOOKDOSE                1595
#define IDC_SPINCOOKDOSE                1596
#define IDC_COOKDOSERATE                1597
#define IDC_COOKTOTALTIME               1598
#define IDC_TILTFORCOOK                 1599
#define IDC_EDITCOOKTILT                1600
#define IDC_STATDOSETIME                1601
#define IDC_RADIODOSE                   1602
#define IDC_RADIOTIME                   1603
#define IDC_EDITCOOKTIME                1604
#define IDC_SPINCOOKTIME                1605
#define IDC_SETBEAMSTATE                1606
#define IDC_STATACBPCTC2                1607
#define IDC_AUTOCENSPOT                 1608
#define IDC_SPINACBSPOT                 1609
#define IDC_SPINACBBINNING              1610
#define IDC_EDITACBEXPOSURE             1611
#define IDC_RADIOUSEEDGE                1612
#define IDC_RADIOUSECENTROID            1613
#define IDC_STATCAMLABEL2               1614
#define IDC_STATACBBINNING              1615
#define IDC_SPINACBMAG                  1616
#define IDC_STATACBMAG                  1617
#define IDC_STATSOURCE                  1618
#define IDC_COOKGO                      1619
#define IDC_BUTREADSEC                  1620
#define IDC_NA_COOKSPECIMEN             1621
#define IDC_NA_CENTERBEAM               1622
#define IDC_SAVETIFF                    1623
#define IDC_STATCOMPRESS                1624
#define IDC_RNOCOMPRESS                 1625
#define IDC_RZIPCOMPRESS                1626
#define IDC_RZLWCOMPRESS                1627
#define IDC_RLZWCOMPRESS                1628
#define IDC_BUTSWAPXY                   1629
#define IDC_RMRCFILE                    1630
#define IDC_RTIFFFILE                   1631
#define IDC_RADOCFILE                   1632
#define IDC_STATCAMNAME                 1633
#define IDC_BUTNEXTSEC                  1634
#define IDC_BUTPREVSEC                  1635
#define IDC_GainGroupBox                1636
#define IDC_CameraAttGroup              1637
#define IDC_CAMTEMP                     1638
#define IDC_CAMBACKPLATETEMP            1639
#define IDC_CAMPRESSURE                 1640
#define IDC_AttenCombo                  1641
#define IDC_INST_MODEL                  1642
#define IDC_Shutter_Delay               1643
#define IDC_PreExposureDelay            1644
#define IDC_CCDSetPoint                 1645
#define IDC_WindowHeater                1646
#define IDC_TIME_STAMP                  1647
#define IDC_HEAD_SERIAL                 1648
#define IDC_ShutterSetButton            1649
#define IDC_ShutterCloseEdit            1650
#define IDC_ShutterBoxEdit              1651
#define IDC_ReadPressure                1652
#define IDC_CHILLERFLOW                 1653
#define IDC_CHECK_OVERLAY               1655
#define IDC_EDIT_OVERLAY                1656
#define IDC_STAT_OVERLAY1               1657
#define IDC_STAT_OVERLAY2               1659
#define IDC_NA_SENDEMAIL                1660
#define IDC_RADIOREGMODE                1661
#define IDC_RADIOTSRLOWDOSE             1662
#define IDC_TSR_EUCENTRICITY            1663
#define IDC_TSR_WALKUP                  1664
#define IDC_TSR_AUTOFOCUS               1665
#define IDC_EDIT_TSR_LOWANGLE           1666
#define IDC_EDIT_TSR_HIGHANGLE          1667
#define IDC_EDIT_TSR_INCANGLE           1668
#define IDC_RADIO_TSRTRIAL              1669
#define IDC_RADIO_TSRRECORD             1670
#define IDC_RADIO_TSRPREVIEW            1671
#define IDC_RADIO_TSR_BOTHDIR           1674
#define IDC_RADIO_TSR_MINUSDIR          1675
#define IDC_RADIO_TSR_PLUSDIR           1676
#define IDC_BUTUSEANGLE                 1677
#define IDC_TSS_PLUS1                   1678
#define IDC_TSS_PLUS2                   1679
#define IDC_TSS_PLUS3                   1680
#define IDC_TSS_PLUS4                   1681
#define IDC_TSS_PLUS5                   1682
#define IDC_TSS_PLUS6                   1683
#define IDC_TSS_PLUS7                   1684
#define IDC_TSS_PLUS8                   1685
#define IDC_TSS_PLUS9                   1686
#define IDC_TSS_PLUS10                  1687
#define IDC_TSS_PLUS11                  1688
#define IDC_TSS_PLUS12                  1689
#define IDC_TSS_NEXT1                   1690
#define IDC_TSS_NEXT2                   1691
#define IDC_TSS_NEXT3                   1692
#define IDC_TSS_NEXT4                   1693
#define IDC_TSS_NEXT5                   1694
#define IDC_TSS_NEXT6                   1695
#define IDC_TSS_NEXT7                   1696
#define IDC_TSS_NEXT8                   1697
#define IDC_TSS_NEXT9                   1698
#define IDC_TSS_NEXT10                  1699
#define IDC_TSS_NEXT11                  1700
#define IDC_TSS_NEXT12                  1701
#define IDC_TSS_PREV1                   1702
#define IDC_TSS_PREV2                   1703
#define IDC_TSS_PREV3                   1704
#define IDC_TSS_PREV4                   1705
#define IDC_TSS_PREV5                   1706
#define IDC_TSS_PREV6                   1707
#define IDC_TSS_PREV7                   1708
#define IDC_TSS_PREV8                   1709
#define IDC_TSS_PREV9                   1710
#define IDC_TSS_PREV10                  1711
#define IDC_TSS_PREV11                  1712
#define IDC_TSS_PREV12                  1713
#define IDC_TSS_TITLE1                  1714
#define IDC_TSS_TITLE2                  1715
#define IDC_TSS_TITLE3                  1716
#define IDC_TSS_TITLE4                  1717
#define IDC_TSS_TITLE5                  1718
#define IDC_TSS_TITLE6                  1719
#define IDC_TSS_TITLE7                  1720
#define IDC_TSS_TITLE8                  1721
#define IDC_TSS_TITLE9                  1722
#define IDC_TSS_TITLE10                 1723
#define IDC_TSS_TITLE11                 1724
#define IDC_TSS_TITLE12                 1725
#define IDC_TSS_LINE1                   1726
#define IDC_TSS_LINE2                   1727
#define IDC_TSS_LINE3                   1728
#define IDC_TSS_LINE4                   1729
#define IDC_TSS_LINE5                   1730
#define IDC_TSS_LINE6                   1731
#define IDC_TSS_LINE7                   1732
#define IDC_TSS_LINE8                   1733
#define IDC_TSS_LINE9                   1734
#define IDC_TSS_LINE10                  1735
#define IDC_TSS_LINE11                  1736
#define IDC_TSS_LINE12                  1737
#define IDC_STATENDAT                   1739
#define IDC_STATDELAY                   1740
#define IDC_STATDELSEC                  1741
#define IDC_STATLIMITIS                 1742
#define IDC_STATISMICRONS               1743
#define IDC_STATPOWER                   1744
#define IDC_STATDEFTARG                 1745
#define IDC_STATTARGMICRONS             1746
#define IDC_STATBEAMTILT                1747
#define IDC_STATFOCUSOFFSET             1748
#define IDC_STATOFFSETMICRONS           1749
#define IDC_STATPCTIMAGE                1750
#define IDC_STATGETTRACK                1751
#define IDC_STATPCTFIELD                1752
#define IDC_STATTRACKWHEN               1753
#define IDC_STATREPFOCUSUM              1754
#define IDC_STATDOFOCUSUM               1755
#define IDC_BUT_TSS_LEFT                1756
#define IDC_BUT_TSS_RIGHT               1757
#define IDC_STATDOAUTOFOC               1758
#define IDC_TSS_VERTLINE                1759
#define IDC_BUT_TSS_PREV                1760
#define IDC_BUT_TSS_NEXT                1761
#define IDC_CHECK_NAV_FILEATITEM        1762
#define IDC_CHECK_NAV_FILEATGROUP       1763
#define IDC_BUT_TSS_FULL                1764
#define IDC_BUT_NAV_STATE               1765
#define IDC_BUT_NAV_TSPARAMS            1766
#define IDC_BUT_NAV_FILENAME            1767
#define IDC_STAT_NAV_FILENAME           1768
#define IDC_STAT_NAV_HORIZLINE          1769
#define IDC_BUT_UPDATEZ                 1770
#define IDC_NA_RUN_TS                   1771
#define IDC_CHECK_MONTTOOPEN            1772
#define IDC_NA_ACQUIRE_TS               1773
#define IDC_NA_PREMACRO                 1774
#define IDC_LIST_STATES                 1775
#define IDC_BUT_ADDCURSTATE             1776
#define IDC_BUT_ADDNAVSTATE             1777
#define IDC_BUT_DELSTATE                1778
#define IDC_BUT_SETIMSTATE              1779
#define IDC_BUT_SETMAPSTATE             1780
#define IDC_BUT_RESTORESTATE            1781
#define IDC_BUT_FORGETSTATE             1782
#define IDC_EDIT_STATENAME              1783
#define IDC_CHECK_DUALMAP               1784
#define IDC_BUT_DUAL_MAP                1785
#define IDC_STAT_NAVITEMNUM             1786
#define IDC_BUT_AC_MORE                 1787
#define IDC_BUT_AC_LESS                 1788
#define IDC_CHECK_AUTO_NEW_LOG          1789
#define IDC_BUT_CLOSE_KEEP              1790
#define IDC_BUT_SETSCHEDSTATE           1791
#define IDC_LD_ROTATE_AXIS              1792
#define IDC_STAT_LD_DEG                 1793
#define IDC_SAVEMDOC                    1794
#define IDC_ROPEN_FOR_SINGLE            1795
#define IDC_ROPEN_FOR_MONTAGE           1796
#define IDC_STAT_TITLELINE              1797
#define IDC_CHECK_FIT_POLY              1798
#define IDC_MATCH_REG_PIXEL             1799
#define IDC_MATCH_REG_INTENSITY         1800
#define IDC_CHECK_USE_HQ_SETTINGS       1801
#define IDC_STAT_HQSTAGEBOX             1802
#define IDC_CHECK_FOCUS_EACH            1803
#define IDC_CHECK_FOCUS_BLOCKS          1804
#define IDC_STAT_BLOCKSIZE              1805
#define IDC_SPIN_BLOCK_SIZE             1806
#define IDC_STATBLOCKPIECES             1807
#define IDC_CHECK_REALIGN               1808
#define IDC_EDITREALIGN                 1809
#define IDC_STAT_DELAY                  1810
#define IDC_STATREALIGNPIECES           1811
#define IDC_EDITDELAY                   1812
#define IDC_STATDELAYSEC                1813
#define IDC_CHECK_SKIPCORR              1814
#define IDC_EDITMINOVERLAP              1815
#define IDC_STATMINAND                  1816
#define IDC_STATMINMICRON               1817
#define IDC_STATTOTALLABEL              1818
#define IDC_BUT_RESET_OVERLAPS          1819
#define IDC_EDITMAXALIGN                1820
#define IDC_STATMAXALIGN                1821
#define IDC_COLLAPSE_GROUPS             1822
#define IDC_NA_GROUP_FOCUS              1823
#define IDC_CHECK_MB_VALVES             1824
#define IDC_EDIT_MB_MINUTES             1825
#define IDC_BUT_UPDATESTATE             1826
#define IDC_BUT_UPDATE_STATE            1827
#define IDC_BUT_NAV_FILEPROPS           1828
#define IDC_CHECK_NAV_TS                1829
#define IDC_STATSPOTLABEL               1830
#define IDC_STATISORPS                  1831
#define IDC_CHECK_SEARCH_RANGE          1832
#define IDC_BUT_ALIGN_TO_MAP            1833
#define IDC_EDIT_CENTER_ANGLE           1834
#define IDC_EDIT_TSV_ANGLE              1835
#define IDC_CHECK_TSV_PLUS_MINUS        1836
#define IDC_TSV_FIXED_VALUE             1837
#define IDC_TSV_LINEAR_CHANGE           1838
#define IDC_TSV_EXPOSURE                1839
#define IDC_TSV_DRIFT                   1840
#define IDC_TSV_DEFOCUS                 1841
#define IDC_TSV_ENERGY                  1842
#define IDC_EDIT_TSV_VALUE              1843
#define IDC_TSV_SLIT_WIDTH              1844
#define IDC_LIST_TSV_TABLE              1845
#define IDC_BUT_TSV_ADD_ITEM            1846
#define IDC_BUT_TSV_REMOVE              1847
#define IDC_CHECK_VARY_PARAMS           1848
#define IDC_BUT_SET_CHANGES             1849
#define IDC_EDIT_SEARCH_RANGE           1850
#define IDC_CHANGE_ALL_EXP              1851
#define IDC_CHANGE_SETTLING             1852
#define IDC_CHANGE_EXPOSURE             1853
#define IDC_BUT_TSV_ADD_SERIES          1854
#define IDC_EDIT_TSV_SERIES_STEP        1855
#define IDC_SPIN_TSV_SERIES_POWER       1856
#define IDC_STAT_SERIES_POWER           1857
#define IDC_AUTOCEN_AT_INTERVAL         1858
#define IDC_EDIT_AC_INTERVAL            1859
#define IDC_AUTOCEN_AT_CROSSING         1860
#define IDC_EDIT_AC_ANGLE               1861
#define IDC_STAT_ACMINUTES              1862
#define IDC_STAT_ACDEGREES              1863
#define IDC_BUT_APPLY_IS                1864
#define IDC_BUT_TRANSFORM               1866
#define IDC_EDIT_AXISANGLE              1867
#define IDC_ZERO_VIEW_SHIFT             1868
#define IDC_STAT_NA_PREMACNUM           1869
#define IDC_SPIN_NA_PREMACNUM           1870
#define IDC_STAT_NA_PREMACNAME          1871
#define IDC_BUT_SWAP_ANGLES             1872
#define IDC_DIM_DO_MESSAGE              1873
#define IDC_DIM_TERM_NOT_BOX            1874
#define IDC_STAT_DIM_TERM_NOT_BOX       1875
#define IDC_STAT_TILT_FAIL              1876
#define IDC_STAT_LD_LOSS                1877
#define IDC_STAT_LD_DIM                 1878
#define IDC_OPPOSITETRIAL               1879
#define IDC_SPIN_TRIAL_BIN              1880
#define IDC_CHECK_TRIAL_BIN             1881
#define IDC_STAT_TRIAL_BIN              1882
#define IDC_GRPCHANGES                  1883
#define IDC_CHECK_IS_REALIGN            1884
#define IDC_EDIT_IS_REALIGN             1885
#define IDC_CHECK_USE_ANCHOR            1886
#define IDC_SPIN_ANCHOR_MAG             1887
#define IDC_STAT_ANCHOR_MAG             1888
#define IDC_CHECK_REPEAT_FOCUS          1889
#define IDC_EDIT_NMPERSEC               1890
#define IDC_STATNMPERSEC                1891
#define IDC_COOLCAM                     1892
#define IDC_WARMCAM                     1893
#define IDC_CorrectionType              1894
#define ID_DE_autosaverawFrames         1895
#define IDC_DDD_Temp                    1898
#define ID_DE_waterlineTemp             1899
#define IDC_PrevDataSet                 1906
#define IDC_NextDataSet                 1907
#define IDC_CAM_STATUS                  1908
#define IDC_MaxFPS                      1909
#define IDC_AttenCombo4K                1911
#define IDC_BlankButton                 1912
#define IDC_BLANKSTATE                  1914
#define IDC_UnBlankButton               1915
#define IDC_CamVoltage                  1916
#define IDC_DSI_Sample_Time             1917
#define IDC_WEB_URL                     1919
#define IDC_FocusCameraSelection        1921
#define IDC_TrialSelectionCamera        1922
#define IDC_EDIT_URL                    1924
#define IDC_CAMTEMP_CAM1                1925
#define IDC_CAMTEMP_CAM2                1926
#define IDC_CAMTEMP_CAM3                1927
#define IDC_CAMTEMP_CAM4                1928
#define IDC_CAMBACKPLATETEMP_CAM1       1929
#define IDC_CAMBACKPLATETEMP_CAM2       1930
#define IDC_CAMBACKPLATETEMP_CAM3       1931
#define IDC_CAMBACKPLATETEMP_CAM4       1932
#define IDC_CAMPRESSURE_CAM1            1933
#define IDC_CAMPRESSURE_CAM2            1934
#define IDC_CAMPRESSURE_CAM3            1935
#define IDC_CAMPRESSURE_CAM4            1936
#define IDC_INST_MODEL_CAM1             1937
#define IDC_INST_MODEL_CAM2             1938
#define IDC_INST_MODEL_CAM3             1939
#define IDC_INST_MODEL_CAM4             1940
#define IDC_HEAD_SERIAL_CAM1            1941
#define IDC_HEAD_SERIAL_CAM2            1942
#define IDC_HEAD_SERIAL_CAM3            1943
#define IDC_HEAD_SERIAL_CAM4            1944
#define IDC_Shutter_Delay_CAM1          1945
#define IDC_Shutter_Delay_CAM2          1946
#define IDC_Shutter_Delay_CAM3          1947
#define IDC_Shutter_Delay_CAM4          1948
#define IDC_PreExposureDelay_CAM1       1949
#define IDC_PreExposureDelay_CAM2       1950
#define IDC_PreExposureDelay_CAM3       1951
#define IDC_PreExposureDelay_CAM4       1952
#define IDC_CCDSetPoint_CAM1            1953
#define IDC_CCDSetPoint_CAM2            1954
#define IDC_CCDSetPoint_CAM3            1955
#define IDC_CCDSetPoint_CAM4            1956
#define IDC_CamVoltage_CAM1             1957
#define IDC_CamVoltage_CAM2             1958
#define IDC_CamVoltage_CAM3             1959
#define IDC_CamVoltage_CAM4             1960
#define IDC_DSI_Sample_Time_CAM1        1961
#define IDC_DSI_Sample_Time_CAM2        1962
#define IDC_DSI_Sample_Time_CAM3        1963
#define IDC_DSI_Sample_Time_CAM4        1964
#define IDC_WindowHeater_CAM1           1965
#define IDC_WindowHeater_CAM2           1966
#define IDC_WindowHeater_CAM3           1967
#define IDC_WindowHeater_CAM4           1968
#define IDC_RunFlat8K                   1969
#define IDC_CORR_SEC                    1970
#define IDC_CORRECTED                   1971
#define IDC_FLAT_STATUS                 1972
#define IDC_STATPARAMBOX                1973
#define IDC_STATPARAMTEXT               1974
#define IDC_STATACQUIS                  1975
#define IDC_STATPOSIT                   1976
#define IDC_STATPROC                    1977
#define IDC_STATEXPTIME                 1978
#define IDC_STATSHUTTER                 1979
#define IDC_STATAREA                    1980
#define IDC_STATSEC1                    1981
#define IDC_STATTOP                     1982
#define IDC_STATLEFT                    1983
#define IDC_STATBOT                     1984
#define IDC_STATRIGHT                   1985
#define IDC_COMBOCHAN1                  1986
#define IDC_COMBOCHAN2                  1987
#define IDC_COMBOCHAN3                  1988
#define IDC_COMBOCHAN4                  1989
#define IDC_COMBOCHAN5                  1990
#define IDC_COMBOCHAN6                  1991
#define IDC_COMBOCHAN7                  1992
#define IDC_COMBOCHAN8                  1993
#define IDC_STATCHANACQ                 1994
#define IDC_STATCHAN1                   1995
#define IDC_STATCHAN2                   1996
#define IDC_STATCHAN3                   1997
#define IDC_STATCHAN4                   1998
#define IDC_STATCHAN5                   1999
#define IDC_STATCHAN6                   2000
#define IDC_STATCHAN7                   2001
#define IDC_STATCHAN8                   2002
#define IDC_CHECK_DYNFOCUS              2003
#define IDC_MATCH_STEM_PIXEL            2004
#define IDC_CHECK_STEM_MODE             2005
#define IDC_CHECK_INVERT_CONTRAST       2006
#define IDC_CHECK_ROTATE_TO_TEM         2007
#define IDC_EDIT_ADDED_ROT              2008
#define IDC_INVERT_CON                  2009
#define ID_DE_autosaveSummedImages      2010
#define IDC_RemapImages                 2011
#define IDC_ANTIALIAS                   2012
#define IDC_CHECK_LINESYNC              2013
#define IDC_SCREEN_SWITCH_STEM          2014
#define IDC_NCMIRITEM1                  2015
#define IDC_NCMIRITEM2                  2016
#define IDC_NCMIRITEM3                  2017
#define IDC_NCMIRITEM4                  2018
#define ID_DE_camName                   2019
#define IDC_RCAMERA1                    2036
#define IDC_RCAMERA2                    2037
#define IDC_RCAMERA3                    2038
#define IDC_RCAMERA4                    2039
#define IDC_RCAMERA5                    2040
#define IDC_RCAMERA6                    2041
#define IDC_BUT_MAX_SCAN_RATE           2042
#define IDC_STAT_SCANRATE               2043
#define IDC_BUT_SET_IS_NEUTRAL          2045
#define IDC_KEEP_PIXEL_TIME             2046
#define IDC_RETRACT_TO_UNBLANK          2047
#define IDC_BLANK_IN_STEM               2048
#define IDC_UNBLANK_STEM                2049
#define IDC_STAT_ADD_SHIFT_BOX          2052
#define IDC_CONFIRM_LOWDOSE_REPEAT      2053
#define IDC_STAT_INTERSET               2054
#define IDC_STAT_TIMING_AVAIL           2055
#define IDC_RETRACT_UNBLANK             2056
#define IDC_OTHERCHANNELS               2057
#define IDC_STAT_K2MODE                 2058
#define IDC_RLINEAR                     2059
#define IDC_RCOUNTING                   2060
#define IDC_RBACKLASH_AUTO              2061
#define IDC_RDE_LINEAR                  2062
#define IDC_RBACKLASH_ASK               2063
#define IDC_RBACKLASH_NONE              2064
#define IDC_EDIT_MIN_FIELD              2065
#define IDC_STAT_MIN_FIELD              2066
#define IDC_STAT_MICRONS                2067
#define IDC_RSUPERRES                   2068
#define IDC_DOSE_FRAC_MODE              2069
#define IDC_STAT_FRAME_TIME             2070
#define IDC_EDIT_FRAME_TIME             2071
#define IDC_ALIGN_DOSE_FRAC             2072
#define IDC_STAT_FRAME_SEC              2073
#define IDC_COMBOFILTER                 2074
#define IDC_SAVE_FRAMES                 2075
#define IDC_ONE_FRAME_PER_FILE          2076
#define IDC_SET_SAVE_FOLDER             2077
#define IDC_STAT_IMAGE_REDUCE           2078
#define IDC_EDIT_READOUTS               2079
#define IDC_STAT_ANTIALIAS              2080
#define IDC_CHECK_USE_VIEW_IN_LOWDOSE   2081
#define IDC_SHOW_ACQUIRE_AREA           2082
#define IDC_CORRECT_BACKLASH            2083
#define IDC_SLIDER_BLACK                2084
#define IDC_SLIDER_WHITE                2085
#define IDC_CHECK_SKIP_REBLANK          2086
#define IDC_STATDOSERATE                2087
#define IDC_TSV_FRAME_TIME              2088
#define IDC_CHECK_TSV_NFRAMES_FIXED     2089
#define IDC_EDIT_EXPOSURE               2090
#define IDC_STAT_NUM_FRAMES             2091
#define IDC_SPIN_NUM_FRAMES             2092
#define IDC_STAT_SKIP_START             2093
#define IDC_SPIN_SKIP_START             2094
#define IDC_SPIN_SKIP_END               2095
#define IDC_SPIN_TOTAL_SAVE             2096
#define IDC_STAT_SKIP_END               2097
#define IDC_SPIN_SKIP_AFTER             2098
#define IDC_EDIT_BIDIR_END_DIFF         2099
#define IDC_SETUP_FALCON_FRAMES         2100
#define IDC_GROUP_DE_SAVE               2101
#define IDC_DE_SAVE_FRAMES              2102
#define IDC_DE_SAVE_SUMS                2103
#define IDC_DE_SAVE_FINAL               2104
#define IDC_EDIT_DE_SUM_COUNT           2105
#define IDC_STAT_NUM_DE_RAW             2106
#define IDC_STAT_NUM_DE_SUMS            2107
#define IDC_DE_insertCam                2108
#define IDC_BUT_FILE_OPTIONS            2109
#define IDC_STAT_DETECTOR               2110
#define IDC_STAT_AUTOSAVE_DIR           2111
#define IDC_STAT_PROT_COV               2112
#define IDC_STAT_PROT_DELAY             2113
#define IDC_STAT_FPSLABEL               2114
#define IDC_STAT_FPSMAX_LABEL           2115
#define IDC_STAT_FORMAT_LABEL           2116
#define IDC_PACK_RAW_FRAME              2117
#define IDC_SAVE_MRC                    2118
#define IDC_COMPRESSED_TIFF             2119
#define IDC_TIFF_ZIP_COMPRESS           2120
#define IDC_STAT_SAVE_SUMMARY           2121
#define IDC_DO_BIDIR                    2123
#define IDC_BIDIR_ANGLE                 2124
#define IDC_BIDIR_WALK_BACK             2125
#define IDC_STAT_BDMAG_LABEL            2126
#define IDC_STAT_BIDIR_MAG              2127
#define IDC_SPIN_BIDIR_MAG              2128
#define IDC_BIDIR_USE_VIEW              2129
#define IDC_CHECK_END_BIDIR             2130
#define IDC_EDIT_BIDIR_ABS_ANGLE        2131
#define IDC_STAT_BIDIR_FIELD_SIZE       2132
#define IDC_SHIFT_MACRO_UP              2133
#define IDC_SHIFT_MACRO_DOWN            2134
#define IDC_STAT_COMPLETIONS            2135
#define IDC_SKIP_ROTFLIP                2136
#define IDC_STATSTAGEx                  2137
#define IDC_STATSTAGEY                  2138
#define IDC_IMAGE_AFTER_MOVE            2139
#define IDC_STAT_TOTAL_SAVE             2140
#define IDC_EDIT_MODE                   2141
#define IDC_STAT_INTENSITY              2142
#define IDC_STAT_C23IA                  2143
#define IDC_STAT_PCTUM                  2144
#define IDC_STAT_STAGEX                 2145
#define IDC_STAT_STAGEY                 2146
#define IDC_STAT_STAGEZ                 2147
#define IDC_STAT_ZLABEL                 2148
#define IDC_AUTOSAVE_RAW                2150
#define IDC_STATINTEGRATION             2151
#define IDC_EDITINTEGRATION             2152
#define IDC_SPININTEGRATION             2153
#define IDC_STATEXPTIMESINT             2154
#define IDC_STAT_FILETYPE               2155
#define IDC_STAT_COMPTITLE              2156
#define IDC_STAT_USE_COMP               2157
#define IDC_STAT_FOLDER                 2158
#define IDC_STAT_FILE                   2159
#define IDC_CHECK_ROOT_FOLDER           2160
#define IDC_CHECK_SAVEFILE_FOLDER       2161
#define IDC_CHECK_NAVLABEL_FOLDER       2162
#define IDC_CHECK_ROOT_FILE             2163
#define IDC_EDIT_BASENAME               2164
#define IDC_CHECK_SAVEFILE_FILE         2165
#define IDC_CHECK_NAVLABEL_FILE         2166
#define IDC_CHECK_NUMBER                2167
#define IDC_CHECK_MONTHDAY              2168
#define IDC_CHECK_HOUR_MIN_SEC          2169
#define IDC_STAT_EXAMPLE                2170
#define IDC_STAT_MUST_EXIST             2171
#define IDC_EDIT_START_NUMBER           2172
#define IDC_CHECK_ONLY_ACQUIRE          2173
#define IDC_STAT_MUST_EXIST2            2174
#define IDC_CHECK_TILT_ANGLE            2175
#define IDC_BUT_NAME_SUFFIX             2176
#define IDC_STAT_DIGITS                 2177
#define IDC_SPIN_DIGITS                 2178
#define IDC_STAT_DOSERATE               2179
#define IDC_STAT_UBPIX                  2180
#define IDC_CHECK_KEEP_ANCHOR           2181
#define IDC_CHECK_CORRECT_DRIFT         2182
#define IDC_STAT_SUBFRAME_TIME          2183
#define IDC_BUT_EQUALIZE                2184
#define IDC_STAT_ENDLABEL               2185
#define IDC_STAT_STARTLABEL             2186
#define IDC_EDIT_SUBFRAME_TIME          2187
#define IDC_SAVE_FRAME_SUMS             2188
#define IDC_SETUP_K2_FRAME_SUMS         2189
#define IDC_ALWAYS_ANTIALIAS            2190
#define IDC_STAT_NANOPROBE              2191
#define IDC_STAT_NORM_DSDF              2192
#define IDC_PACK_COUNTING_4BIT          2193
#define IDC_USE_4BIT_MRC_MODE           2194
#define IDC_BUTMIDDLE                   2195
#define IDC_BUT_NANO_MICRO              2196
#define IDC_STAT_ALIGN_METHOD           2197
#define IDC_RPAIRWISE_NUM               2198
#define IDC_RPAIRWISE_HALF              2199
#define IDC_RPAIRWISE_ALL               2200
#define IDC_RACCUM_REF                  2201
#define IDC_SPIN_PAIRWISE_NUM           2202
#define IDC_STAT_PAIRWISE_NUM           2203
#define IDC_STAT_FRAME_LABEL            2204
#define IDC_STAT_CUTOFF_LABEL           2205
#define IDC_EDIT_CUTOFF                 2206
#define IDC_STAT_ALIGN_BIN              2207
#define IDC_SPIN_ALIGN_BIN              2208
#define IDC_REFINE_ALIGNMENT            2209
#define IDC_SPIN_REFINE_ITER            2210
#define IDC_STAT_REFINE_ITER            2211
#define IDC_STAT_ITER_LABEL             2212
#define IDC_GROUP_FRAMES                2213
#define IDC_STAT_GROUP_SIZE             2214
#define IDC_SPIN_GROUP_SIZE             2215
#define IDC_STAT_GROUP_NEEDS            2216
#define IDC_SMOOTH_SHIFTS               2217
#define IDC_STAT_SMOOTH_CRIT            2218
#define IDC_SPIN_SMOOTH_CRIT            2219
#define IDC_STAT_SMOOTH_LABEL           2220
#define IDC_USE_GPU                     2221
#define IDC_REFINE_GROUPS               2222
#define IDC_STAT_REFINE_CUTOFF          2223
#define IDC_EDIT_REFINE_CUTOFF          2224
#define IDC_EDIT_MAX_SHIFT              2225
#define IDC_STAT_MAX_SHIFT              2226
#define IDC_STAT_PIXEL_LABEL            2227
#define IDC_TRUNCATE_ABOVE              2228
#define IDC_EDIT_TRUNCATION             2229
#define IDC_STAT_COUNT_LABEL            2230
#define IDC_EDIT_CUTOFF2                2231
#define IDC_EDIT_CUTOFF3                2232
#define IDC_HYBRID_SHIFTS               2233
#define IDC_EDIT_SIGMA_RATIO            2234
#define IDC_STAT_STOP_ITER              2235
#define IDC_STAT_SIGMA_RATIO            2236
#define IDC_EDIT_STOP_ITER              2237
#define IDC_STAT_STOP_LABEL             2238
#define IDC_USE_FRAME_ALIGN             2239
#define IDC_RALIGN_IN_DM                2240
#define IDC_RWITH_IMOD                  2241
#define IDC_STAT_FILTER                 2242
#define IDC_LIST_SET_NAMES              2244
#define IDC_STAT_PARAM_NAME             2245
#define IDC_EDIT_NAME                   2246
#define IDC_STAT_MORE_PARAMS            2247
#define IDC_STAT_WHERE_ALIGN            2248
#define IDC_STAT_OTHER_CUTS             2249
#define IDC_BUT_DELETE_SET              2250
#define IDC_BUT_SET_FOLDER              2251
#define IDC_KEEP_PRECISION              2252
#define IDC_SAVE_FLOAT_SUMS             2253
#define IDC_WHOLE_SERIES                2254
#define IDC_SAVE_TIMES_100              2255
#define IDC_EDIT_MAX_DELTA_EXP          2256
#define IDC_STAT_MAX_DELTA1             2257
#define IDC_STAT_MAX_DELTA2             2258
#define IDC_STAT_INTERMEDIATE_ONOFF     2259
#define IDC_SPIN_RCMAG                  2261
#define IDC_SPIN_RCSPOT                 2262
#define IDC_STAT_RCC2IA                 2263
#define IDC_SPIN_RCINTENSITY            2264
#define IDC_SPIN_RCBEAM                 2265
#define IDC_BUT_VALVES                  2266
#define IDC_BUT_DELBEAMPLUS             2267
#define IDC_BUT_DELBEAMMINUS            2268
#define IDC_BUT_DELC2PLUS               2269
#define IDC_BUT_DELC2MINUS              2270
#define IDC_STAT_BEAMDELTA              2271
#define IDC_STAT_C2DELTA                2272
#define IDC_SPIN_BEAM_LEFT_RIGHT        2273
#define IDC_FIND_IN_MACRO               2274
#define IDC_BUT_NEW_PARAMS              2275
#define IDC_BUT_SETUP_ALIGN             2276
#define IDC_CHECK_END_HIGH_EXP          2277
#define IDC_CHECK_MAGINTENSITY          2278
#define IDC_DRAW_LABELS                 2279
#define IDC_COMBO_PREMACRO              2280
#define IDC_COMBO_MACRO                 2281
#define IDC_CHECK_LIMIT_ABS_FOCUS       2282
#define IDC_CHECK_LIMIT_DELTA_FOCUS     2283
#define IDC_EDIT_FOCUS_MAX_DELTA        2284
#define IDC_STAT_DELTA_MICRONS          2285
#define IDC_CHECK_NO_DRIFT_CORR         2286
#define IDC_CHECK_CONTINUOUS_MODE       2287
#define IDC_EDIT_CONTIN_DELAY_FAC       2288
#define IDC_RMONTAGE                    2290
#define IDC_RSEARCH_OFFSET              2291
#define IDC_SAVE_UNNORMALIZED           2292
#define IDC_STAT_MESSAGE                2293
#define IDC_STAT_GRAY_PANEL             2294
#define IDC_STAT_NUM_EARLY_FRAMES       2295
#define IDC_SPIN_EARLY_FRAMES           2296
#define IDC_STAT_ALIGN_SUMMARY          2297
#define IDC_USE_VIEW_IN_SEARCH          2298
#define IDC_DO_EARLY_RETURN             2299
#define IDC_USE_EXTENSION_MRCS          2300
#define IDC_STAT_SAVING_FATE            2301
#define IDC_STAT_FILE_SAVING_INTO       2302
#define IDC_STAT_EXPLANATION            2303
#define IDC_RJPEGCOMPRESS               2304
#define IDC_NA_DO_SUBSET                2305
#define IDC_EDIT_SUBSET_START           2306
#define IDC_EDIT_SUBSET_END             2307
#define IDC_NA_SKIP_INITIAL_MOVE        2308
#define IDC_NA_SKIP_Z_MOVES             2309
#define IDC_ONLY_IN_PLUGIN              2310
#define IDC_ONLY_WITH_IMOD              2311
#define IDC_ONLY_NON_SUPER              2312
#define IDC_ONLY_SUPERRESOLUTION        2313
#define IDC_ALIGN_SUBSET                2314
#define IDC_RVIEWOFFSET                 2315
#define IDC_STAT_SUBSET_TO              2317
#define IDC_STAT_SUBSET_PAREN           2318
#define IDC_STAT_USE_ONLY_GROUP         2319
#define IDC_STAT_LINE1                  2320
#define IDC_FA_EDIT_SUB_START           2321
#define IDC_FA_EDIT_SUB_END             2322
#define IDC_RSEARCH                     2323
#define IDC_RVIEW_OFFSET                2324
#define IDC_CHECK_USE_SEARCH_IN_LD      2325
#define IDC_CHECK_USE_MONT_MAP_PARAMS   2326
#define IDC_STAT_LINE2                  2327
#define IDC_USE_FRAME_FOLDER            2328
#define IDC_STAT_MIN_FRAME_TIME         2329
#define IDC_STAT_NUM_SHOTS              2330
#define IDC_SPIN_NUM_SHOTS              2331
#define IDC_RNO_CENTER                  2332
#define IDC_RCENTER_AFTER               2333
#define IDC_RCENTER_BEFORE              2334
#define IDC_EDIT_SPOKE_DIST             2335
#define IDC_STAT_MAX_FRAME_TIME         2336
#define IDC_EDIT_EARLY_FRAMES           2337
#define IDC_CHECK_SAVE_RECORD           2338
#define IDC_STAT_BEAM_DIAM              2339
#define IDC_EDIT_BEAM_DIAM              2340
#define IDC_STAT_BEAM_UM                2341
#define IDC_CHECK_USE_ILLUM_AREA        2342
#define IDC_STAT_NUM_EARLY              2343
#define IDC_STAT_EARLY_GROUP            2344
#define IDC_RNO_EARLY                   2345
#define IDC_RLAST_EARLY                 2346
#define IDC_RALL_EARLY                  2347
#define IDC_EDIT_EXTRA_DELAY            2348
#define IDC_STAT_DEFPS                  2349
#define IDC_EDIT_DE_FPS                 2350
#define IDC_STAT_DE_FRAME_TIME          2351
#define IDC_EDIT_DE_FRAME_TIME          2352
#define IDC_STAT_DE_SUM_NUM             2353
#define IDC_SPIN_DE_SUM_NUM             2354
#define IDC_DE_SAVE_MASTER              2355
#define IDC_STAT_DE_FRAME_SEC           2357
#define IDC_STAT_PROC_TYPE              2358
#define IDC_RLINEAR_REF                 2359
#define IDC_RPRE_COUNTING               2360
#define IDC_RPOST_COUNTING              2361
#define IDC_STAT_REF_TYPE               2362
#define IDC_RDARK_REF                   2363
#define IDC_RGAIN_REF                   2364
#define IDC_STAT_REF_FPS                2365
#define IDC_EDIT_REF_EXPOSURE           2366
#define IDC_SPIN_NUM_REPEATS            2368
#define IDC_EDIT_NUM_REPEATS            2369
#define IDC_STAT_GAIN_ADVICE            2370
#define IDC_USE_HARDWARE_BIN            2371
#define IDC_STAT_DEMODE                 2372
#define IDC_RDE_COUNTING                2373
#define IDC_RDE_SUPERRES                2374
#define IDC_DE_ALIGN_FRAMES             2375
#define IDC_DE_SET_SAVE_FOLDER          2376
#define IDC_STAT_DE_WHERE_ALIGN         2377
#define IDC_BUT_DE_SETUP_ALIGN          2378
#define IDC_EDIT_ONE_LINE               2379
#define IDC_EDIT_ONE_LINE2              2380
#define IDC_EDIT_ONE_LINE3              2381
#define IDC_EDIT_ONE_LINE4              2382
#define IDC_EDIT_ONE_LINE5              2383
#define IDC_SKIP_FILE_DLG               2385
#define IDC_RSUPER_RES_REF              2386
#define ID_NEW_IMAGE                    32771
#define IDM_FILE_SAVEOTHER              32772
#define IDM_FILE_READ                   32773
#define IDM_FILE_OPENNEW                32775
#define IDM_FILE_OPENOLD                32776
#define ID_FILE_MONTAGESETUP            32777
#define IDM_FILE_MONTAGESETUP           32778
#define IDM_FILE_CLOSE                  32779
#define IDM_FILE_SAVEACTIVE             32780
#define IDM_FILE_TRUNCATION             32781
#define IDM_FILE_READOTHER              32783
#define IDM_FILE_SAVE                   32784
#define ID_RESIZE_MAIN                  32785
#define ID_CAMERA_PARAMETERS            32786
#define ID_CAMERA_ACQUIRE               32787
#define ID_CAMERA_VIEW                  32788
#define ID_CAMERA_FOCUS                 32789
#define ID_CAMERA_TRIAL                 32790
#define ID_CAMERA_RECORD                32791
#define ID_CAMERA_SCREENDOWN            32792
#define ID_CAMERA_SIMULATION            32793
#define ID_CAMERA_STOPACQUIRE           32794
#define ID_SETTINGS_OPEN                32795
#define ID_SETTINGS_REREAD              32796
#define ID_SETTINGS_SAVE                32797
#define ID_SETTINGS_SAVEAS              32798
#define ID_SETTINGS_CLOSE               32799
#define ID_SETTINGS_RESTOREDEFAULTS     32800
#define ID_SETTINGS_READAGAIN           32801
#define ID_SETTINGS_READDEFAULTS        32802
#define ID_SETTINGS_SAVECALIBRATIONS    32803
#define ID_CALIBRATION_IMAGESHIFT       32804
#define ID_FILE_OVERWRITE               32805
#define ID_FILE_READPIECE               32806
#define ID_CAMERA_MONTAGE               32807
#define ID_CAMERA_MONTAGETRIAL          32808
#define IDM_AUTOALIGN                   32809
#define IDM_TILTUP                      32810
#define IDM_TILTDOWN                    32811
#define ID_FILE_OPENLOG                 32812
#define ID_FILE_SAVELOG                 32813
#define ID_CALIBRATION_AUTOFOCUS        32814
#define ID_CALIBRATION_ADMINISTRATOR    32815
#define ID_FOCUS_SETTARGET              32816
#define ID_FOCUS_MEASUREDEFOCUS         32817
#define ID_FOCUS_AUTOFOCUS              32818
#define ID_FOCUS_SETBEAMTILT            32819
#define ID_FOCUS_SETTHRESHOLD           32820
#define ID_FOCUS_REPORTSHIFTDRIFT       32821
#define ID_FOCUS_DRIFTPROTECTION        32822
#define ID_MACRO_EDIT1                  32823
#define ID_MACRO_EDIT2                  32824
#define ID_MACRO_EDIT3                  32825
#define ID_MACRO_EDIT4                  32826
#define ID_MACRO_EDIT5                  32827
#define ID_MACRO_EDIT6                  32828
#define ID_MACRO_EDIT7                  32829
#define ID_MACRO_EDIT8                  32830
#define ID_MACRO_EDIT9                  32831
#define ID_MACRO_EDIT10                 32832
#define ID_MACRO_STOP                   32843
#define ID_MACRO_END                    32844
#define ID_MACRO_RESUME                 32845
#define ID_MACRO_CONTROLS               32846
#define ID_CALIBRATION_SETSHIFTDELAY    32847
#define ID_CALIBRATION_SETFOCUSRANGE    32848
#define IDM_CAMERATOGGLE                32861
#define IDM_ESCAPE                      -32674
#define ID_WINDOW_RESIZEMAIN            32863
#define ID_FILE_SAVELOGAS               32864
#define ID_CALIBRATION_BEAMINTENSITY    32865
#define ID_PROCESS_MINMAXMEAN           32866
#define ID_PROCESS_FFT                  32867
#define ID_PROCESS_BINNEDFFT            32868
#define ID_PROCESS_ROTATELEFT           32869
#define ID_PROCESS_ROTATERIGHT          32870
#define ID_EUCENTRICITY_COARSE          32871
#define ID_EUCENTRICITY_FINE            32872
#define ID_EUCENTRICITY_BOTH            32873
#define ID_CALIBRATION_ISFROMSCRATCH    32874
#define ID_REVERSE_TILT                 32875
#define ID_PROCESS_ZEROTILTMEAN         32876
#define ID_CAMERA_POSTACTIONS           32878
#define ID_TASKS_TILTSERIES             32879
#define ID_PROCESS_SETINTENSITY         32880
#define ID_TASKS_FINEREALIGN            32881
#define ID_FOCUS_MOVEFOCUSCENTER        32882
#define ID_FOCUS_MOVECENTER             32883
#define ID_TILTSERIES_STOP              32884
#define ID_TILTSERIES_ENDLOOP           32885
#define ID_TILTSERIES_RESUME            32886
#define ID_TILTSERIES_BACKUP            32887
#define ID_TILTSERIES_ONELOOP           32888
#define ID_TILTSERIES_ONESTEP           32889
#define ID_TILTSERIES_TERMINATE         32890
#define ID_FOCUS_VERBOSE                32891
#define ID_TASKS_VERBOSE                32892
#define ID_TILTSERIES_VERBOSE           32893
#define ID_CAMERA_PREVIEW               32894
#define ID_CALIBRATION_BEAMSHIFT        32895
#define ID_PROCESS_MOVEBEAM             32896
#define ID_CAMERA_SETTIMING             32897
#define ID_CAMERA_DEBUGMODE             32898
#define ID_CAMERA_NEWGAINREF            32899
#define ID_CAMERA_SHOWGAINREF           32900
#define ID_CAMERA_SHOWDARKREF           32901
#define ID_CALIBRATION_MAGENERGYSHIFTS  32902
#define ID_PROCESS_FIXDARKXRAYS         32903
#define ID_PROCESS_SETDARKCRITERIA      32905
#define ID_CAMERA_ACQUIREGAINREF        32907
#define ID_FOCUS_CHECKAUTOFOCUS         32908
#define ID_TILTSERIES_DEBUGMODE         32909
#define ID_CALIBRATION_LISTMAGS         32910
#define ID_TILTSERIES_AUTOSAVELOG       32911
#define ID_FOCUS_REPORTONEXISTING       32912
#define ID_FOCUS_SETOFFSET              32913
#define ID_TASKS_WALKUPANCHOR           32914
#define ID_CALIBRATION_DISTORTION       32915
#define ID_CALIBRATION_STAGESHIFT       32916
#define ID_TASKS_NAVIGATOR              32917
#define ID_LOAD_NAV_FILE                32920
#define ID_NAVIGATOR_CLOSE              32921
#define IDC_NAVIGATOR_ACQUIRE           32923
#define ID_CALIBRATION_ELECTRONDOSE     32924
#define ID_CALIBRATION_C2FACTOR         32925
#define ID_FILE_SET16BITPOLICY          32926
#define ID_CALIBRATION_BEAMCROSSOVER    32927
#define ID_CALIBRATION_SETOVERLAPS      32928
#define ID_NAVIGATOR_AUTOSAVE           32929
#define ID_SETTINGS_AUTOSAVE            32930
#define ID_NAVIGATOR_SETUPFULLMONTAGE   32931
#define ID_TASKS_SETTILTAXISOFFSET      32932
#define ID_CAMERA_DIVIDEBY2             32933
#define ID_CALIBRATION_CAMERATIMING     32935
#define ID_CAMERA_SETCORRECTIONS        32936
#define ID_CAMERA_NORMALIZEHERE         32937
#define ID_FOCUS_RESETDEFOCUS           32938
#define ID_TASKS_SETITERATIONLIMIT      32939
#define ID_TASKS_USETRIALINLD           32940
#define ID_NAVIGATOR_CONVERTMAPSTOBYTES 32941
#define ID_CAMERA_SETSCANNING           32942
#define ID_CALIBRATION_NEUTRALISVALUES  32943
#define ID_FILE_SETSIGNEDPOLICY         32944
#define ID_CALIBRATION_SPOTINTENSITY    32945
#define ID_CALIBRATION_PURGEOLDCALIBS   32946
#define ID_NAVIGATOR_SKEWEDSUPERMONTAGE 32947
#define ID_NAVIGATOR_ALIGNEDSUPERMONTAGE 32948
#define ID_CALIBRATION_LISTISVECTORS    32949
#define ID_FILE_READAPPEND              32950
#define ID_PROCESS_FIXIMAGEXRAYS        32951
#define ID_PROCESS_SETIMAGECRITERIA     32952
#define ID_CALIBRATION_LISTSTAGECALS    32953
#define ID_CALIBRATION_SHUTTERDEADTIME  32954
#define ID_PROCESS_SHOWCROSSCORR        32955
#define ID_CALIBRATION_SETDEBUGOUTPUT   32956
#define ID_SETTINGS_MRU_FILE1           32957
#define ID_SETTINGS_MRU_FILE2           32958
#define ID_SETTINGS_MRU_FILE3           32959
#define ID_SETTINGS_MRU_FILE4           32960
#define ID_SETTINGS_MRU_FILE5           32961
#define ID_SETTINGS_MRU_FILE6           32962
#define ID_SETTINGS_MRU_FILE7           32963
#define ID_SETTINGS_MRU_FILE8           32964
#define ID_FILE_NEWMONTAGE              32965
#define ID_TILTSERIES_EXTRAOUTPUT       32966
#define ID_PROCESS_LIVEFFT              32967
#define ID_NAVIGATOR_RUNMACROATAREAS    32968
#define ID_Menu                         32969
#define ID_FOCUS_SHOWEXISTINGCORR       32970
#define ID_NAVIGATOR_CHANGEREGISTRATION 32979
#define ID_CALIBRATION_MAGISOFFSETS     32980
#define ID_CALIBRATION_EFTEMISOFFSET    32981
#define ID_TASKS_CENTERBEAM             32982
#define ID_NAVIGATOR_ROTATEMAP          32987
#define ID_NAVIGATOR_ALIGNTOITEM        32988
#define ID_NAVIGATOR_SHIFTBYLASTERROR   32989
#define ID_NAVIGATOR_REALIGNACQUIRE     32990
#define ID_NAVIGATOR_SHIFTTOMARKER      32991
#define ID_NAVIGATOR_UNDOLASTSHIFT      32992
#define ID_NAVIGATOR_LOADUNBINNED       32994
#define ID_NAVIGATOR_SETGRIDLIMITS      32995
#define ID_CALIBRATION_STANDARDLMFOCUS  32996
#define ID_CAMERA_GAINREFPOLICY         32998
#define ID_TILTSERIES_RESETPOLEANGLE    32999
#define ID_MACRO_TOOLBAR                33000
#define ID_Menu33001                    33001
#define ID_TILTSERIES_SETUPFUTURE       33002
#define ID_TILTSERIES_FUTUREPOLICIES    33003
#define ID_NAVIGATOR_ENDACQUIRE         33004
#define ID_PROCESS_CIRCLEONLIVEFFT      33005
#define ID_NAVIGATOR_RESTORESTATE       33008
#define ID_NAVIGATOR_SETACQUIRESTATE    33009
#define ID_TASKS_SETINCREMENTS          33010
#define ID_NAVIGATOR_READSTOCKSTATES    33011
#define ID_NAVIGATOR_ADDCIRCLEPOLYGON   33013
#define ID_NAVIGATOR_DELETESUPERMONTAGE 33014
#define ID_NAVIGATOR_SUPERMONTAGING     33015
#define ID_SUPERMONTAGING_POLYGONSUPERMONTAGE 33016
#define ID_MACRO_RUN1                   33017
#define ID_MACRO_RUN2                   33018
#define ID_MACRO_RUN3                   33019
#define ID_MACRO_RUN4                   33020
#define ID_MACRO_RUN5                   33021
#define ID_MACRO_RUN6                   33022
#define ID_MACRO_RUN7                   33023
#define ID_MACRO_RUN8                   33024
#define ID_MACRO_RUN9                   33025
#define ID_MACRO_RUN10                  33026
#define ID_MACRO_RUN11                  33027
#define ID_MACRO_RUN12                  33028
#define ID_MACRO_RUN13                  33029
#define ID_MACRO_RUN14                  33030
#define ID_MACRO_RUN15                  33031
#define ID_MACRO_RUN16                  33032
#define ID_MACRO_RUN17                  33033
#define ID_MACRO_RUN18                  33034
#define ID_MACRO_RUN19                  33035
#define ID_MACRO_RUN20                  33036
#define ID_MACRO_SET                    33037
#define ID_MACRO_SETLENGTH              33038
#define ID_NAVIGATOR_IMPORTMAP          33039
#define ID_NAVIGATOR_UNDOTRANSFORMATION 33040
#define ID_MONTAGE_DEFINEFILETOOPEN     33041
#define ID_NAVIGATOR_ADDGRIDOFPOINTS    33042
#define ID_MONTAGE_LISTFILESTOOPEN      33043
#define ID_CAMERA_SETCOUNTLIMIT         33044
#define ID_TASKS_SETUPCOOKER            33045
#define ID_TASKS_COOKSPECIMEN           33046
#define ID_TASKS_SETUPAUTOCENTER        33047
#define ID_TASKS_AUTOCENTERBEAM         33048
#define ID_CALIBRATION_USESHORT         33051
#define ID_PROCESS_FINDPIXELSIZE        33053
#define ID_PROCESS_PIXELSIZEFROMMARKER  33054
#define ID_CAMERA_SETDRIFTINTERVAL      33055
#define ID_FILE_CONTINUOUSSAVE          33056
#define ID_MACRO_VERBOSE                33057
#define ID_TILTSERIES_SENDEMAIL         33060
#define ID_TILTSERIES_SETADDRESS        33061
#define ID_PROCESS_MAKECOLOROVERLAY     33062
#define ID_TASKS_ASSESSANGLERANGE       33063
#define ID_NAVIGATOR_OPENSTATEDLG       33064
#define ID_NAVIGATOR_GROUP_ACQUIRE      33066
#define ID_TASKS_TRIAL_IN_LD_REFINE     33069
#define ID_NAVIGATOR_ALIGN_TO_MAP       33071
#define ID_CAMERA_INTERPOLATE_DARK_REFS 33073
#define ID_PROCESS_CROPIMAGE            33074
#define ID_CALIBRATION_STAGESTRETCH     33075
#define ID_PROCESS_LISTRELATIVEROTATIONS 33076
#define ID_NEW_MAP                      33085
#define ID_NAVIGATOR_ACQUIRE            33086
#define ID_DELETEITEM                   33087
#define ID_SAVE_NAV_FILE                33088
#define ID_SAVEAS_NAV_FILE              33089
#define ID_CORNER_MONTAGE               33090
#define ID_POLYGON_MONTAGE              33091
#define ID_TRANSFORM_PTS                33092
#define ID_TASKS_WALKUP                 33094
#define ID_RESET_REALIGN                33095
#define ID_MACRO_EDIT15                 33096
#define ID_MACRO_EDIT20                 33097
#define ID_CALIBRATION_SET_IS_DELAY_FACTOR 33099
#define ID_NAVIGATOR_POLYGON_FROM_CORNERS 33101
#define ID_CALIBRATION_STEMFOCUSVSZ     33103
#define ID_TASKS_ASSESS_INTERSET_SHIFTS 33108
#define ID_TASKS_REVISE_CANCEL          33110
#define ID_NAVIGATOR_REALIGN_SCALING    33112
#define ID_CALIBRATION_QUICK_FLYBACK_TIME 33114
#define ID_PROCESS_SETBINNEDSIZE        33115
#define ID_NAVIGATOR_ADJUST_BACKLASH    33117
#define ID_NAVIGATOR_BACKLASHSETTINGS   33118
#define ID_TASKS_USE_VIEW_IN_LOWDOSE    33120
#define ID_CALIBRATION_ALPHA_BEAM_SHIFTS 33122
#define ID_PROCESS_AUTOCORRELATION      33123
#define ID_DE_autosaveF                 33124
#define ID_DE_preExpTime                33125
#define ID_DE_sensorDelay               33126
#define ID_DE_currfps                   33127
#define ID_DE_maxfps                    33128
#define ID_DE_failsafe                  33129
#define ID_DE_protectMode               33130
#define ID_DE_coverDelay                33131
#define ID_DE_autosaveCorRaw            33132
#define ID_DE_autosaveCorrSum           33133
#define ID_DE_saveDir                   33134
#define ID_DE_temperSet                 33135
#define ID_DE_PROPERTY_EXPAND           33141
#define ID_DE_cameraPos                 33143
#define ID_DE_insertCam                 33144
#define ID_DE_retractCam                33145
#define ID_DE_antosaveFinal             33146
#define ID_CALIBRATION_SET_APERTURE_SIZE 33148
#define ID_CAMERA_SAVERAWPACKED         33149
#define ID_FOCUS_SET_TILT_DIRECTION     33151
#define ID_CALIBRATION_WHOLE_IMAGE_CORR 33153
#define ID_CALIBRATION_SET_CYCLE_LENGTHS 33159
#define ID_CALIBRATION_BEAMSPOT         33160
#define ID_CALIBRATION_PIXELSIZE        33162
#define ID_PIXELSIZE_ADD_TO_ROTATION    33164
#define ID_MACRO_RUN                    33165
#define ID_RUN_RUN11                    33166
#define ID_MACRO_RUN21                  33167
#define ID_MACRO_RUN22                  33168
#define ID_MACRO_RUN23                  33169
#define ID_MACRO_RUN24                  33170
#define ID_MACRO_RUN25                  33171
#define ID_MACRO_RUN26                  33172
#define ID_MACRO_RUN27                  33173
#define ID_MACRO_RUN28                  33174
#define ID_MACRO_RUN29                  33175
#define ID_TASKS_SETDOSERATE            33176
#define ID_TASKS_SET_DOSE_RATE          33177
#define ID_FILE_CLOSE_MDOC              33180
#define ID_FILE_OPEN_MDOC               33181
#define ID_MACRO_READMANY               33182
#define ID_MACRO_WRITEALL               33183
#define ID_TILTSERIES_CALL_TS_PLUGIN    33185
#define ID_SETTINGS_SPECIALOPTIONS      33186
#define ID_SPECIAL_PIEZO_FOR_LD_AXIS_SHIFT 33189
#define ID_SPECIAL_SKIP_BEAM_SHIFT_IN_TS 33190
#define ID_TASKS_SPECIALOPTIONS         33191
#define ID_PIXELSIZE_CATALASE_CRYSTAL   33193
#define ID_NAVIGATOR_MERGEFILE          33194
#define ID_CAMERA_SPECIALSETTINGS       33195
#define ID_SPECIALSETTINGS_SETQUALITY   33196
#define ID_CAMERA_SET_QUALITY           33197
#define ID_WINDOW_STAGE_MOVE_TOOL       33199
#define ID_PROCESS_CROP_AVERAGE         33201
#define ID_NAVIGATOR_FORCE_CENTER_ALIGN 33203
#define ID_SPECIAL_DISABLE_DARK_TRIM_IN_ALIGN 33206
#define ID_AUTOFOCUSFOCUS_LISTCALIBRATIONS 33207
#define ID_FOCUS_SET_DDD_MIN_BINNING    33209
#define ID_FOCUS_SET_FILTER_CUTOFFS     33212
#define ID_CALIBRATION_BASEFOCUS        33213
#define ID_AUTOFOCUSFOCUS_BASEFOCUSVALUES 33214
#define ID_CALIBRATION_RESTORENEUTRALIS 33215
#define ID_PIXELSIZE_MESHFORGRIDBARS    33216
#define ID_BEAMSPOT_SPOTBEAMSHIFTS      33217
#define ID_BEAMSPOT_RESTORESPOTSHIFTS   33218
#define ID_SPECIALOPTIONS_ALLOWCONTINUOUSINTASKS 33219
#define ID_SPECIALOPTIONS_NORMALIZEVIAVIEWFORAU 33220
#define ID_MONTAGINGGRIDS_GROUPPOINTSINGRID 33221
#define ID_MONTAGINGGRIDS_SETGROUPSIZE  33222
#define ID_FOCUS_SHOWEXISTINGSTRETCH    33223
#define ID_IMAGESTAGESHIFT_USETRIALBINNING 33224
#define ID_IMAGESTAGESHIFT_USETRIALSIZE 33225
#define ID_PROCESS_SIDE                 33226
#define ID_PROCESS_SIDE_BY_SIDE         33227
#define ID_IMAGESTAGESHIFT_REMOVEISCAL  33229
#define ID_IMAGESTAGESHIFT_REMOVESTAGECAL 33230
#define ID_SPECIALOPTIONS_ADJUSTFOCUSONPROBEMODECHANGE 33231
#define ID_TILTSERIES_SAVEX             33232
#define ID_CAMERA_NONORMOFDSDOSEFRAC    33233
#define ID_TILTSERIES_AUTOSAVEX         33234
#define ID_MACRO_LISTFUNCTIONS          33235
#define ID_AUTOFOCUSFOCUS_ASTIGMATI     33236
#define ID_AUTOFOCUSFOCUS_COMA          33237
#define ID_FOCUS_CORRECTASTIGMATISM     33238
#define ID_FOCUS_COMA                   33239
#define ID_AUTOFOCUSFOCUS_SETUPCOMA     33240
#define ID_AUTOFOCUSFOCUS_SETUPASTIGMATISM 33241
#define ID_FOCUS_SETASTIGBEAMTILT       33242
#define ID_FOCUS_SETCOMABEAMTILT        33243
#define ID_TILTSERIES_PRE               33244
#define ID_TILTSERIES_RUN_MACRO         33245
#define ID_TILTSERIES_SETMACROTORUN     33246
#define ID_CAMERA_CORRELATIONFILTER     33247
#define ID_CORRELATIONFILTER_USEFILTERSET2 33248
#define ID_CORRELATIONFILTER_USESET2INLOWDOSE 33249
#define ID_CORRELATIONFILTER_DIVIDESET1BY2 33250
#define ID_CORRELATIONFILTER_DIVIDEFILTERSET2BY2 33251
#define ID_CORRELATIONFILTER_TESTSET1VALUES 33252
#define ID_CORRELATIONFILTER_TESTSET2VALUES 33253
#define ID_CORRELATIONFILTER_REDOCORRWHENREAD 33254
#define ID_IMAGESTAGESHIFT_DOFOCUS      33255
#define ID_CALIBRATION_HIGH             33256
#define ID_CALIBRATION_HIGH_DEFOCUS     33257
#define ID_CALIBRATION_LISTFOCUS        33258
#define ID_PROCESS_AUTOMATICFFTS        33259
#define ID_PROCESS_SETPHASEPLATESHIFT   33260
#define ID_PROCESS_SETDEFOCUSFORCIRCLES 33261
#define ID_TILTSERIES_FIXED             33262
#define ID_TILTSERIES_FIXED_NUM_FRAMES  33263
#define ID_NAVIGATOR_WRITEASXMLFILE     33264
#define ID_WINDOW_SHOWSCOPECONTROLPANEL 33265
#define ID_NAVIGATOR_OPTIONS            33266
#define ID_OPTIONS_SETPOINTLABELTHRESHOLD 33267
#define ID_FOCUS_SETABSOLUTELIIMITS     33268
#define ID_FOCUS_USEABSOLUTERANGE       33269
#define ID_FOCUS_TESTWHENUSINGOFFSET    33270
#define ID_CAMERA_SETFRAMEALIGNLINES    33271
#define ID_SETTINGS_SETAPROPERTY        33272
#define ID_FOCUS_SETITERATIONS          33273
#define ID_FOCUS_RUNANOTHERITERATION    33274
#define ID_FOCUS_MAKEZEMLINTABLEAU      33275
#define ID_FOCUS_SETCOMAITERATIONS      33276
#define ID_SCRIPT_SETINDENTSIZE         33277
#define ID_SPECIALOPTIONS_NORMALIZEALLLENS 33278
#define ID_NAVOPTIONS_USECURRENTLDPARAMSINRI 33279
#define ID_CAMERA_USEVIEWFORSEARCH      33280
#define ID_CAMERA_USERECORDFORMONTAGE   33281
#define ID_CAMERA_SEARCH                33282
#define ID_SCRIPT_CLEARPERSISTENTVARS   33284
#define ID_OPTIONS_SHOWMULTI            33285
#define ID_OPTIONS_SETMULTI             33286
#define ID_Menu33287                    33287
#define ID_SCRIPT_RUNONECOMMAND         33288
#define ID_FILE_SKIPFILEPROPERTIESDIALOG 33289

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        228
#define _APS_NEXT_COMMAND_VALUE         33290
#define _APS_NEXT_CONTROL_VALUE         2387
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
