/* soapStub.h
   Generated by gSOAP 2.7.3 from .\webserviceCommands.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_ns__getCurrentTiltAngleResponse
#define SOAP_TYPE_ns__getCurrentTiltAngleResponse (17)
/* ns:getCurrentTiltAngleResponse */
struct ns__getCurrentTiltAngleResponse
{
	float result;	/* RPC return element */	/* required element of type xsd:float */
};
#endif

#ifndef SOAP_TYPE_ns__getCurrentTiltAngle
#define SOAP_TYPE_ns__getCurrentTiltAngle (18)
/* ns:getCurrentTiltAngle */
struct ns__getCurrentTiltAngle
{
	int a;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__setTiltAngleResponse
#define SOAP_TYPE_ns__setTiltAngleResponse (20)
/* ns:setTiltAngleResponse */
struct ns__setTiltAngleResponse
{
	float result;	/* RPC return element */	/* required element of type xsd:float */
};
#endif

#ifndef SOAP_TYPE_ns__setTiltAngle
#define SOAP_TYPE_ns__setTiltAngle (21)
/* ns:setTiltAngle */
struct ns__setTiltAngle
{
	float tilt;	/* required element of type xsd:float */
};
#endif

#ifndef SOAP_TYPE_ns__setXYStagePositionResponse
#define SOAP_TYPE_ns__setXYStagePositionResponse (23)
/* ns:setXYStagePositionResponse */
struct ns__setXYStagePositionResponse
{
	float r;	/* RPC return element */	/* required element of type xsd:float */
};
#endif

#ifndef SOAP_TYPE_ns__setXYStagePosition
#define SOAP_TYPE_ns__setXYStagePosition (24)
/* ns:setXYStagePosition */
struct ns__setXYStagePosition
{
	float x;	/* required element of type xsd:float */
	float y;	/* required element of type xsd:float */
};
#endif

#ifndef SOAP_TYPE_ns__setZResponse
#define SOAP_TYPE_ns__setZResponse (26)
/* ns:setZResponse */
struct ns__setZResponse
{
	float result;	/* RPC return element */	/* required element of type xsd:float */
};
#endif

#ifndef SOAP_TYPE_ns__setZ
#define SOAP_TYPE_ns__setZ (27)
/* ns:setZ */
struct ns__setZ
{
	float z;	/* required element of type xsd:float */
};
#endif

#ifndef SOAP_TYPE_ns__getXResponse
#define SOAP_TYPE_ns__getXResponse (29)
/* ns:getXResponse */
struct ns__getXResponse
{
	float result;	/* RPC return element */	/* required element of type xsd:float */
};
#endif

#ifndef SOAP_TYPE_ns__getX
#define SOAP_TYPE_ns__getX (30)
/* ns:getX */
struct ns__getX
{
	float x;	/* required element of type xsd:float */
};
#endif

#ifndef SOAP_TYPE_ns__getYResponse
#define SOAP_TYPE_ns__getYResponse (32)
/* ns:getYResponse */
struct ns__getYResponse
{
	float result;	/* RPC return element */	/* required element of type xsd:float */
};
#endif

#ifndef SOAP_TYPE_ns__getY
#define SOAP_TYPE_ns__getY (33)
/* ns:getY */
struct ns__getY
{
	float y;	/* required element of type xsd:float */
};
#endif

#ifndef SOAP_TYPE_ns__getZResponse
#define SOAP_TYPE_ns__getZResponse (35)
/* ns:getZResponse */
struct ns__getZResponse
{
	float result;	/* RPC return element */	/* required element of type xsd:float */
};
#endif

#ifndef SOAP_TYPE_ns__getZ
#define SOAP_TYPE_ns__getZ (36)
/* ns:getZ */
struct ns__getZ
{
	float z;	/* required element of type xsd:float */
};
#endif

#ifndef SOAP_TYPE_ns__setXResponse
#define SOAP_TYPE_ns__setXResponse (38)
/* ns:setXResponse */
struct ns__setXResponse
{
	float result;	/* RPC return element */	/* required element of type xsd:float */
};
#endif

#ifndef SOAP_TYPE_ns__setX
#define SOAP_TYPE_ns__setX (39)
/* ns:setX */
struct ns__setX
{
	float x;	/* required element of type xsd:float */
};
#endif

#ifndef SOAP_TYPE_ns__setYResponse
#define SOAP_TYPE_ns__setYResponse (41)
/* ns:setYResponse */
struct ns__setYResponse
{
	float result;	/* RPC return element */	/* required element of type xsd:float */
};
#endif

#ifndef SOAP_TYPE_ns__setY
#define SOAP_TYPE_ns__setY (42)
/* ns:setY */
struct ns__setY
{
	float y;	/* required element of type xsd:float */
};
#endif

#ifndef SOAP_TYPE_ns__NextMosaicMoveResponse
#define SOAP_TYPE_ns__NextMosaicMoveResponse (44)
/* ns:NextMosaicMoveResponse */
struct ns__NextMosaicMoveResponse
{
	float result;	/* RPC return element */	/* required element of type xsd:float */
};
#endif

#ifndef SOAP_TYPE_ns__NextMosaicMove
#define SOAP_TYPE_ns__NextMosaicMove (45)
/* ns:NextMosaicMove */
struct ns__NextMosaicMove
{
	int MoveType;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__QueryMosaicImagesResponse
#define SOAP_TYPE_ns__QueryMosaicImagesResponse (48)
/* ns:QueryMosaicImagesResponse */
struct ns__QueryMosaicImagesResponse
{
	int result;	/* RPC return element */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__QueryMosaicImages
#define SOAP_TYPE_ns__QueryMosaicImages (49)
/* ns:QueryMosaicImages */
struct ns__QueryMosaicImages
{
	int Type;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__BeginMosaicResponse
#define SOAP_TYPE_ns__BeginMosaicResponse (51)
/* ns:BeginMosaicResponse */
struct ns__BeginMosaicResponse
{
	int result;	/* RPC return element */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__BeginMosaic
#define SOAP_TYPE_ns__BeginMosaic (52)
/* ns:BeginMosaic */
struct ns__BeginMosaic
{
	int MosaicType;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__CheckifOk2AcquireResponse
#define SOAP_TYPE_ns__CheckifOk2AcquireResponse (54)
/* ns:CheckifOk2AcquireResponse */
struct ns__CheckifOk2AcquireResponse
{
	int result;	/* RPC return element */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__CheckifOk2Acquire
#define SOAP_TYPE_ns__CheckifOk2Acquire (55)
/* ns:CheckifOk2Acquire */
struct ns__CheckifOk2Acquire
{
	int MosaicType;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__SerialGotAcquireTokenResponse
#define SOAP_TYPE_ns__SerialGotAcquireTokenResponse (57)
/* ns:SerialGotAcquireTokenResponse */
struct ns__SerialGotAcquireTokenResponse
{
	int result;	/* RPC return element */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns__SerialGotAcquireToken
#define SOAP_TYPE_ns__SerialGotAcquireToken (58)
/* ns:SerialGotAcquireToken */
struct ns__SerialGotAcquireToken
{
	int confirm;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (61)
/* SOAP Header: */
struct SOAP_ENV__Header
{
	void *dummy;	/* transient */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (62)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (64)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (65)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	char *SOAP_ENV__Reason;	/* optional element of type xsd:string */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (4)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE_xsd__double
#define SOAP_TYPE_xsd__double (7)
typedef double xsd__double;
#endif

#ifndef SOAP_TYPE_xsd__short
#define SOAP_TYPE_xsd__short (9)
typedef short xsd__short;
#endif

#ifndef SOAP_TYPE_xsd__int
#define SOAP_TYPE_xsd__int (10)
typedef int xsd__int;
#endif

#ifndef SOAP_TYPE_xsd__float
#define SOAP_TYPE_xsd__float (12)
typedef float xsd__float;
#endif

#ifndef SOAP_TYPE_xsd__long
#define SOAP_TYPE_xsd__long (13)
typedef float xsd__long;
#endif

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (14)
typedef char *xsd__string;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operations                                                         *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 ns__getCurrentTiltAngle(struct soap*, int a, float &result);

SOAP_FMAC5 int SOAP_FMAC6 ns__setTiltAngle(struct soap*, float tilt, float &result);

SOAP_FMAC5 int SOAP_FMAC6 ns__setXYStagePosition(struct soap*, float x, float y, float &r);

SOAP_FMAC5 int SOAP_FMAC6 ns__setZ(struct soap*, float z, float &result);

SOAP_FMAC5 int SOAP_FMAC6 ns__getX(struct soap*, float x, float &result);

SOAP_FMAC5 int SOAP_FMAC6 ns__getY(struct soap*, float y, float &result);

SOAP_FMAC5 int SOAP_FMAC6 ns__getZ(struct soap*, float z, float &result);

SOAP_FMAC5 int SOAP_FMAC6 ns__setX(struct soap*, float x, float &result);

SOAP_FMAC5 int SOAP_FMAC6 ns__setY(struct soap*, float y, float &result);

SOAP_FMAC5 int SOAP_FMAC6 ns__NextMosaicMove(struct soap*, int MoveType, float &result);

SOAP_FMAC5 int SOAP_FMAC6 ns__QueryMosaicImages(struct soap*, int Type, int &result);

SOAP_FMAC5 int SOAP_FMAC6 ns__BeginMosaic(struct soap*, int MosaicType, int &result);

SOAP_FMAC5 int SOAP_FMAC6 ns__CheckifOk2Acquire(struct soap*, int MosaicType, int &result);

SOAP_FMAC5 int SOAP_FMAC6 ns__SerialGotAcquireToken(struct soap*, int confirm, int &result);

/******************************************************************************\
 *                                                                            *
 * Stubs                                                                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__getCurrentTiltAngle(struct soap *soap, const char *soap_endpoint, const char *soap_action, int a, float &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__setTiltAngle(struct soap *soap, const char *soap_endpoint, const char *soap_action, float tilt, float &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__setXYStagePosition(struct soap *soap, const char *soap_endpoint, const char *soap_action, float x, float y, float &r);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__setZ(struct soap *soap, const char *soap_endpoint, const char *soap_action, float z, float &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__getX(struct soap *soap, const char *soap_endpoint, const char *soap_action, float x, float &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__getY(struct soap *soap, const char *soap_endpoint, const char *soap_action, float y, float &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__getZ(struct soap *soap, const char *soap_endpoint, const char *soap_action, float z, float &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__setX(struct soap *soap, const char *soap_endpoint, const char *soap_action, float x, float &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__setY(struct soap *soap, const char *soap_endpoint, const char *soap_action, float y, float &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__NextMosaicMove(struct soap *soap, const char *soap_endpoint, const char *soap_action, int MoveType, float &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__QueryMosaicImages(struct soap *soap, const char *soap_endpoint, const char *soap_action, int Type, int &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__BeginMosaic(struct soap *soap, const char *soap_endpoint, const char *soap_action, int MosaicType, int &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__CheckifOk2Acquire(struct soap *soap, const char *soap_endpoint, const char *soap_action, int MosaicType, int &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__SerialGotAcquireToken(struct soap *soap, const char *soap_endpoint, const char *soap_action, int confirm, int &result);

/******************************************************************************\
 *                                                                            *
 * Skeletons                                                                  *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getCurrentTiltAngle(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setTiltAngle(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setXYStagePosition(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setZ(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getX(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getY(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getZ(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setX(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__setY(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__NextMosaicMove(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__QueryMosaicImages(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__BeginMosaic(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__CheckifOk2Acquire(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__SerialGotAcquireToken(struct soap*);

#endif

/* End of soapStub.h */
